// Date: 31/01/2013 20:09:23
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.zeuscraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelHarpie extends ModelBase
{
  //fields
    ModelRenderer Wing;
    ModelRenderer head;
    ModelRenderer Shape1;
    ModelRenderer body;
    ModelRenderer Wing1;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
  
  public ModelHarpie()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Wing = new ModelRenderer(this, 88, 0);
      Wing.addBox(0F, -3F, 0F, 15, 6, 1);
      Wing.setRotationPoint(0F, 3.1F, 4.2F);
      Wing.setTextureSize(128, 64);
      Wing.mirror = true;
      setRotation(Wing, 0.6320364F, 0F, 0F);
      head = new ModelRenderer(this, 56, 15);
      head.addBox(-4F, -8F, -4F, 8, 8, 8);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0.0743572F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 36, 0);
      Shape1.addBox(-4F, 0F, 0F, 8, 10, 1);
      Shape1.setRotationPoint(0F, -8.3F, 3.4F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0.0743572F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 8, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 0.5204921F, 0F, 0F);
      Wing1 = new ModelRenderer(this, 0, 0);
      Wing1.addBox(0F, -2.6F, -1F, 15, 6, 1);
      Wing1.setRotationPoint(0F, 2.8F, 4F);
      Wing1.setTextureSize(128, 64);
      Wing1.mirror = true;
      setRotation(Wing1, -0.6320364F, -3.141593F, 0F);
      rightarm = new ModelRenderer(this, 1, 47);
      rightarm.addBox(-3F, -2F, -2F, 4, 12, 4);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(128, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0.0371701F, 0F, 0F);
      leftarm = new ModelRenderer(this, 26, 47);
      leftarm.addBox(-1F, -2F, -2F, 4, 12, 4);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(128, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0.0371701F, 0F, 0F);
      rightleg = new ModelRenderer(this, 53, 47);
      rightleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      rightleg.setRotationPoint(-2F, 10.5F, 6F);
      rightleg.setTextureSize(128, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0.5204921F, 0F, 0F);
      leftleg = new ModelRenderer(this, 80, 47);
      leftleg.addBox(-2F, 0F, -2F, 4, 12, 4);
      leftleg.setRotationPoint(2F, 10.5F, 6F);
      leftleg.setTextureSize(128, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0.5204921F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Wing.render(f5);
    head.render(f5);
    Shape1.render(f5);
    body.render(f5);
    Wing.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
	  this.Wing.rotateAngleY = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.Wing1.rotateAngleY = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
