// Date: 7/22/2013 4:57:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMassospondylus extends ModelBase
{
  //fields
    ModelRenderer Head1;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer Body;
    ModelRenderer Chest;
    ModelRenderer RightLegThigh;
    ModelRenderer RightLegLower1;
    ModelRenderer RightFoot;
    ModelRenderer RightThigh;
    ModelRenderer RightLegLower2;
    ModelRenderer Foot2;
    ModelRenderer Upperarm1;
    ModelRenderer Forearm1;
    ModelRenderer Hand1;
    ModelRenderer Claw1;
    ModelRenderer Upperarm2;
    ModelRenderer Forearm2;
    ModelRenderer Hand2;
    ModelRenderer Claw2;
    ModelRenderer TailBase;
    ModelRenderer Tail;
    ModelRenderer TailMiddle;
    ModelRenderer TailEnd;
    ModelRenderer TailTip;
    ModelRenderer Head2;
    ModelRenderer Head3;
  
  public ModelMassospondylus()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Head1 = new ModelRenderer(this, 0, 17);
      Head1.addBox(-2F, 0F, -10F, 4, 3, 1);
      Head1.setRotationPoint(0F, 0F, -33F);
      Head1.setTextureSize(128, 128);
      Head1.mirror = true;
      setRotation(Head1, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 32, 1);
      Neck1.addBox(0F, 0F, 0F, 4, 4, 18);
      Neck1.setRotationPoint(-2F, -1.5F, -34F);
      Neck1.setTextureSize(128, 128);
      Neck1.mirror = true;
      setRotation(Neck1, -0.2443461F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 77, 1);
      Neck2.addBox(0F, 0F, 0F, 5, 6, 9);
      Neck2.setRotationPoint(-2.5F, 2F, -18F);
      Neck2.setTextureSize(128, 128);
      Neck2.mirror = true;
      setRotation(Neck2, -0.1570796F, 0F, 0F);
      Body = new ModelRenderer(this, 42, 24);
      Body.addBox(-5F, -2F, -3F, 12, 17, 12);
      Body.setRotationPoint(-1F, 10F, 0F);
      Body.setTextureSize(128, 128);
      Body.mirror = true;
      setRotation(Body, 1.570796F, 0F, 0F);
      Chest = new ModelRenderer(this, 1, 24);
      Chest.addBox(0F, -1F, 2F, 10, 10, 10);
      Chest.setRotationPoint(-5F, 13F, -10F);
      Chest.setTextureSize(128, 128);
      Chest.mirror = true;
      setRotation(Chest, 1.48353F, 0F, 0F);
      RightLegThigh = new ModelRenderer(this, 71, 81);
      RightLegThigh.addBox(-4F, -1F, -3F, 3, 12, 7);
      RightLegThigh.setRotationPoint(-3.5F, 5F, 8F);
      RightLegThigh.setTextureSize(128, 128);
      RightLegThigh.mirror = true;
      setRotation(RightLegThigh, 0F, 0F, 0F);
      RightLegLower1 = new ModelRenderer(this, 71, 111);
      RightLegLower1.addBox(-3F, 11F, 0F, 2, 6, 3);
      RightLegLower1.setRotationPoint(-3.5F, 5F, 9F);
      RightLegLower1.setTextureSize(128, 128);
      RightLegLower1.mirror = true;
      setRotation(RightLegLower1, 0F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 71, 120);
      RightFoot.addBox(-3.5F, 16F, -2F, 3, 2, 6);
      RightFoot.setRotationPoint(-3.5F, 6F, 8F);
      RightFoot.setTextureSize(128, 128);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      RightThigh = new ModelRenderer(this, 94, 81);
      RightThigh.addBox(0F, -1F, -3F, 3, 12, 7);
      RightThigh.setRotationPoint(4.5F, 5F, 8F);
      RightThigh.setTextureSize(128, 128);
      RightThigh.mirror = true;
      setRotation(RightThigh, 0F, 0F, 0F);
      RightLegLower2 = new ModelRenderer(this, 94, 110);
      RightLegLower2.addBox(1F, 10F, 1F, 2, 6, 3);
      RightLegLower2.setRotationPoint(3.5F, 6F, 8F);
      RightLegLower2.setTextureSize(128, 128);
      RightLegLower2.mirror = true;
      setRotation(RightLegLower2, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 94, 119);
      Foot2.addBox(0.5F, 16F, -2F, 3, 2, 6);
      Foot2.setRotationPoint(3.5F, 6F, 8F);
      Foot2.setTextureSize(128, 128);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Upperarm1 = new ModelRenderer(this, 93, 44);
      Upperarm1.addBox(-1F, 0F, -1F, 2, 7, 3);
      Upperarm1.setRotationPoint(-4.5F, 8F, -8F);
      Upperarm1.setTextureSize(128, 128);
      Upperarm1.mirror = true;
      setRotation(Upperarm1, 0.5235988F, 0F, 0F);
      Forearm1 = new ModelRenderer(this, 93, 55);
      Forearm1.addBox(0F, 0F, 0F, 1, 7, 2);
      Forearm1.setRotationPoint(-5.5F, 12F, -4F);
      Forearm1.setTextureSize(128, 128);
      Forearm1.mirror = true;
      setRotation(Forearm1, -0.5410521F, -0.1047198F, -0.1745329F);
      Hand1 = new ModelRenderer(this, 93, 65);
      Hand1.addBox(0F, 0F, 0F, 1, 3, 2);
      Hand1.setRotationPoint(-4F, 17.9F, -7.6F);
      Hand1.setTextureSize(128, 128);
      Hand1.mirror = true;
      setRotation(Hand1, -0.3141593F, -0.1570796F, -0.2792527F);
      Claw1 = new ModelRenderer(this, 93, 71);
      Claw1.addBox(0F, 0F, 0F, 2, 3, 0);
      Claw1.setRotationPoint(-4F, 17.9F, -7.6F);
      Claw1.setTextureSize(128, 128);
      Claw1.mirror = true;
      setRotation(Claw1, -0.6108652F, -0.3665191F, -0.2792527F);
      Upperarm2 = new ModelRenderer(this, 104, 44);
      Upperarm2.addBox(0F, 0F, -1F, 2, 7, 3);
      Upperarm2.setRotationPoint(3.5F, 8F, -8F);
      Upperarm2.setTextureSize(128, 128);
      Upperarm2.mirror = true;
      setRotation(Upperarm2, 0.6108652F, 0F, 0F);
      Forearm2 = new ModelRenderer(this, 104, 55);
      Forearm2.addBox(0F, 0F, 0F, 1, 7, 2);
      Forearm2.setRotationPoint(4.5F, 12F, -4F);
      Forearm2.setTextureSize(128, 128);
      Forearm2.mirror = true;
      setRotation(Forearm2, -0.5410521F, 0.0872665F, 0.1745329F);
      Hand2 = new ModelRenderer(this, 104, 65);
      Hand2.addBox(0F, 0F, 0F, 1, 3, 2);
      Hand2.setRotationPoint(3.1F, 17.8F, -7.6F);
      Hand2.setTextureSize(128, 128);
      Hand2.mirror = true;
      setRotation(Hand2, -0.3141593F, 0.1570796F, 0.2792527F);
      Claw2 = new ModelRenderer(this, 104, 71);
      Claw2.addBox(0F, 0F, 0F, 2, 3, 0);
      Claw2.setRotationPoint(2.1F, 17.5F, -7.1F);
      Claw2.setTextureSize(128, 128);
      Claw2.mirror = true;
      setRotation(Claw2, -0.6108652F, 0.3665191F, 0.2792527F);
      TailBase = new ModelRenderer(this, 91, 25);
      TailBase.addBox(0F, 0F, 0F, 8, 8, 10);
      TailBase.setRotationPoint(-4F, 11.5F, 13F);
      TailBase.setTextureSize(128, 128);
      TailBase.mirror = true;
      setRotation(TailBase, 1.570796F, 0F, 0F);
      Tail = new ModelRenderer(this, 1, 54);
      Tail.addBox(0F, 0F, 0F, 6, 8, 14);
      Tail.setRotationPoint(-3F, 2F, 20F);
      Tail.setTextureSize(128, 128);
      Tail.mirror = true;
      setRotation(Tail, -0.0698132F, 0F, 0F);
      TailMiddle = new ModelRenderer(this, 42, 54);
      TailMiddle.addBox(0F, 0F, 0F, 5, 6, 20);
      TailMiddle.setRotationPoint(-2.5F, 4F, 33F);
      TailMiddle.setTextureSize(128, 128);
      TailMiddle.mirror = true;
      setRotation(TailMiddle, -0.1745329F, 0F, 0F);
      TailEnd = new ModelRenderer(this, 1, 81);
      TailEnd.addBox(0F, 0F, 0F, 4, 4, 15);
      TailEnd.setRotationPoint(-2F, 8.5F, 52F);
      TailEnd.setTextureSize(128, 128);
      TailEnd.mirror = true;
      setRotation(TailEnd, -0.0698132F, 0F, 0F);
      TailTip = new ModelRenderer(this, 40, 81);
      TailTip.addBox(0F, 0F, 0F, 3, 3, 12);
      TailTip.setRotationPoint(-1.5F, 10F, 65F);
      TailTip.setTextureSize(128, 128);
      TailTip.mirror = true;
      setRotation(TailTip, -0.0349066F, 0F, 0F);
      Head2 = new ModelRenderer(this, 1, 1);
      Head2.addBox(-2.5F, -2F, -7F, 5, 5, 7);
      Head2.setRotationPoint(0F, 0F, -33F);
      Head2.setTextureSize(128, 128);
      Head2.mirror = true;
      setRotation(Head2, 0F, 0F, 0F);
      Head3 = new ModelRenderer(this, 13, 16);
      Head3.addBox(-2F, -1F, -9F, 4, 4, 3);
      Head3.setRotationPoint(0F, 0F, -33F);
      Head3.setTextureSize(128, 128);
      Head3.mirror = true;
      setRotation(Head3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Head1.render(f5);
    Neck1.render(f5);
    Neck2.render(f5);
    Body.render(f5);
    Chest.render(f5);
    RightLegThigh.render(f5);
    RightLegLower1.render(f5);
    RightFoot.render(f5);
    RightThigh.render(f5);
    RightLegLower2.render(f5);
    Foot2.render(f5);
    Upperarm1.render(f5);
    Forearm1.render(f5);
    Hand1.render(f5);
    Claw1.render(f5);
    Upperarm2.render(f5);
    Forearm2.render(f5);
    Hand2.render(f5);
    Claw2.render(f5);
    TailBase.render(f5);
    Tail.render(f5);
    TailMiddle.render(f5);
    TailEnd.render(f5);
    TailTip.render(f5);
    Head2.render(f5);
    Head3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
