// Date: 1/5/2015 2:10:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelTylo extends ModelBase
{
  //fields
    ModelRenderer LeftBackFinPiece;
    ModelRenderer RightFrontFinPiece;
    ModelRenderer LeftFrontFinPiece;
    ModelRenderer Neck;
    ModelRenderer Body2;
    ModelRenderer Body1;
    ModelRenderer HeadPiece;
    ModelRenderer TailPiece1;
    ModelRenderer RightBackFinPiece;
  ModelRenderer LeftBackFin1;
  ModelRenderer LeftBackFin3;
  ModelRenderer LeftBackFin2;
  ModelRenderer RightFrontFin3;
  ModelRenderer RightFrontFin2;
  ModelRenderer RightFrontFin1;
  ModelRenderer LeftFrontFin1;
  ModelRenderer LeftFrontFin2;
  ModelRenderer LeftFrontFin3;
  ModelRenderer Head;
  ModelRenderer JawsTip;
  ModelRenderer Jaws;
  ModelRenderer Tail1;
 ModelRenderer Tail2;
 ModelRenderer Tail3;
 ModelRenderer TailFin;
 ModelRenderer Tail4;
 ModelRenderer TailPiece2;
 ModelRenderer TailPiece3;
  ModelRenderer RightBackFin3;
  ModelRenderer RightBackFin2;
  ModelRenderer RightBackFin1;
  ModelRenderer TailPiece4;
  
  public ModelTylo()
  {
    textureWidth = 200;
    textureHeight = 119;
    
    LeftBackFinPiece = new ModelRenderer(this, "LeftBackFinPiece");
    LeftBackFinPiece.setRotationPoint(3.5F, 21F, 20F);
    setRotation(LeftBackFinPiece, 0F, 0F, 0F);
    LeftBackFinPiece.mirror = true;
   //   LeftBackFinPiece.addBox("LeftBackFin1", 0F, -1F, -2.5F, 2, 2, 5);
   //   LeftBackFinPiece.addBox("LeftBackFin3", 10F, -0.5F, -3F, 2, 1, 6);
   //   LeftBackFinPiece.addBox("LeftBackFin2", 2F, -0.5F, -3.5F, 8, 1, 7);
    ModelRenderer LeftBackFin1 = new ModelRenderer(this, 31, 92);
    LeftBackFin1.addBox(0F, -1F, -2.5F, 2, 2, 5);
    ModelRenderer LeftBackFin3 = new ModelRenderer(this, 54, 93);
    LeftBackFin3.addBox(10F, -0.5F, -3F, 2, 1, 6);
    ModelRenderer LeftBackFin2 = new ModelRenderer(this, 11, 105);
    LeftBackFin2.addBox(2F, -0.5F, -3.5F, 8, 1, 7);
    
    
    
    
    // modelTylo.addChildModelRenderer(LeftBackFinPiece);
    RightFrontFinPiece = new ModelRenderer(this, "RightFrontFinPiece");
    RightFrontFinPiece.setRotationPoint(-4F, 21F, -17F);
    setRotation(RightFrontFinPiece, 0F, 0F, 0F);
    RightFrontFinPiece.mirror = true;
   //   RightFrontFinPiece.addBox("RightFrontFin3", -12F, -0.5F, -3F, 2, 1, 6);
     // RightFrontFinPiece.addBox("RightFrontFin1", -2F, -1F, -2.5F, 2, 2, 5);
    //  RightFrontFinPiece.addBox("RightFrontFin2", -10F, -0.5F, -3.5F, 8, 1, 7);
    ModelRenderer RightFrontFin3 = new ModelRenderer(this, 71, 87);
    RightFrontFin3.addBox(-12F, -0.5F, -3F, 2, 1, 6);
    ModelRenderer RightFrontFin1 = new ModelRenderer(this, 31, 92);
    RightFrontFin1.addBox(-2F, -1F, -2.5F, 2, 2, 5);
    ModelRenderer RightFrontFin2 = new ModelRenderer(this, 3, 80);
    RightFrontFin2.addBox(-10F, -0.5F, -3.5F, 8, 1, 7);
      
      
      
      
      //  modelTylo.addChildModelRenderer(RightFrontFinPiece);
    LeftFrontFinPiece = new ModelRenderer(this, "LeftFrontFinPiece");
    LeftFrontFinPiece.setRotationPoint(4F, 21F, -17F);
    setRotation(LeftFrontFinPiece, 0F, 0F, 0F);
    LeftFrontFinPiece.mirror = true;
     // LeftFrontFinPiece.addBox("LeftFrontFin1", 0F, -1F, -2.5F, 2, 2, 5);
     // LeftFrontFinPiece.addBox("LeftFrontFin3", 10F, -0.5F, -3F, 2, 1, 6);
     // LeftFrontFinPiece.addBox("LeftFrontFin2", 2F, -0.5F, -3.5F, 8, 1, 7);
    ModelRenderer LeftFrontFin1 = new ModelRenderer(this, 31, 92);
    LeftFrontFin1.addBox(0F, -1F, -2.5F, 2, 2, 5);
    ModelRenderer LeftFrontFin3 = new ModelRenderer(this, 54, 93);
    LeftFrontFin3.addBox(10F, -0.5F, -3F, 2, 1, 6);
    ModelRenderer LeftFrontFin2 = new ModelRenderer(this, 11, 105);
    LeftFrontFin2.addBox(2F, -0.5F, -3.5F, 8, 1, 7);
    
    //  modelTylo.addChildModelRenderer(LeftFrontFinPiece);
      Neck = new ModelRenderer(this, 163, 74);
      Neck.addBox(-4F, -3.5F, -6F, 8, 9, 5);
      Neck.setRotationPoint(0F, 18F, -19F);
      Neck.setTextureSize(200, 119);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      Body2 = new ModelRenderer(this, 40, 56);
      Body2.addBox(0F, 0F, 0F, 7, 9, 18);
      Body2.setRotationPoint(-3.5F, 14F, 5F);
      Body2.setTextureSize(200, 119);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body1 = new ModelRenderer(this, 0, 21);
      Body1.addBox(0F, 0F, 0F, 8, 10, 25);
      Body1.setRotationPoint(-4F, 14F, -20F);
      Body1.setTextureSize(200, 119);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
    HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0F, 18.5F, -25F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
     // HeadPiece.addBox("Head", -3.5F, -3F, -10F, 7, 7, 10);
     // HeadPiece.addBox("JawsTip", -2.5F, -1F, -25F, 5, 5, 7);
      //HeadPiece.addBox("Jaws", -3F, -2F, -18F, 6, 6, 8);
    ModelRenderer Head = new ModelRenderer(this, 59, 0);
    Head.addBox(-3.5F, -3F, -10F, 7, 7, 10);
    ModelRenderer JawsTip = new ModelRenderer(this, 4, 2);
    JawsTip.addBox(-2.5F, -1F, -25F, 5, 5, 7);
    ModelRenderer Jaws = new ModelRenderer(this, 30, 0);
    Jaws.addBox(-3F, -2F, -18F, 6, 6, 8);
  
    
    // modelTylo.addChildModelRenderer(HeadPiece);
    TailPiece1 = new ModelRenderer(this, "TailPiece1");
    TailPiece1.setRotationPoint(0F, 18F, 23F);
    setRotation(TailPiece1, 0F, 0F, 0F);
    TailPiece1.mirror = true;
     // TailPiece1.addBox("Tail1", -3F, -3F, 0F, 6, 7, 18);
    ModelRenderer Tail1 = new ModelRenderer(this, 76, 27);
    Tail1.addBox(-3F, -3F, 0F, 6, 7, 18);
      
      
      
      TailPiece2 = new ModelRenderer(this, "TailPiece2");
    TailPiece2.setRotationPoint(0F, 0F, 18F);
    setRotation(TailPiece2, 0F, 0F, 0F);
    TailPiece2.mirror = true;
     // TailPiece2.addBox("Tail2", -2.5F, -2.5F, 0F, 5, 6, 18);
    ModelRenderer Tail2 = new ModelRenderer(this, 125, 5);
    Tail2.addBox(-2.5F, -2.5F, 0F, 5, 6, 18);
      
      
      TailPiece3 = new ModelRenderer(this, "TailPiece3");
    TailPiece3.setRotationPoint(0F, 0F, 18F);
   setRotation(TailPiece3, -19F, 0F, 0F);
   // setRotation(Tail3, -19F, 0F, 0F);
    TailPiece3.mirror = true;
    //  TailPiece3.addBox("Tail3", -2F, -2F, -1F, 4, 5, 18);
   //   TailPiece3.addBox("TailFin", 0F, -19F, -1F, 0, 18, 25);
   //   TailPiece3.addBox("Tail4", -1F, -1.5F, 17F, 2, 4, 14);
    ModelRenderer Tail3 = new ModelRenderer(this, 144, 39);
    Tail3.addBox(-2F, -2F, -1F, 4, 5, 18);
  
    
 /*   TailPiece4 = new ModelRenderer(this, "TailPiece4");
    TailPiece4.setRotationPoint(0F, 0F, 18F);
   setRotation(TailPiece4, 0F, 0F, 0F);
   // setRotation(Tail3, -19F, 0F, 0F);
    TailPiece4.mirror = true;*/
    ModelRenderer TailFin = new ModelRenderer(this, 80, 72);
    TailFin.addBox(0F, -19F, -1F, 0, 18, 25);
    ModelRenderer Tail4 = new ModelRenderer(this, 116, 71);
    Tail4.addBox(-1F, -1.5F, 17F, 2, 4, 14);
    
    
    // TailPiece2.addChildModelRenderer(TailPiece3);
     // TailPiece1.addChildModelRenderer(TailPiece2);
     // modelTylo.addChildModelRenderer(TailPiece1);
    RightBackFinPiece = new ModelRenderer(this, "RightBackFinPiece");
    RightBackFinPiece.setRotationPoint(-3.5F, 21F, 20F);
    setRotation(RightBackFinPiece, 0F, 0F, 0F);
    RightBackFinPiece.mirror = true;
    //  RightBackFinPiece.addBox("RightBackFin3", -12F, -0.5F, -3F, 2, 1, 6);
   //  RightBackFinPiece.addBox("RightBackFin1", -2F, -1F, -2.5F, 2, 2, 5);
    //  RightBackFinPiece.addBox("RightBackFin2", -10F, -0.5F, -3.5F, 8, 1, 7);
    //  modelTylo.addChildModelRenderer(RightBackFinPiece);
    ModelRenderer RightBackFin3 = new ModelRenderer(this, 71, 87);
    RightBackFin3.addBox(-12F, -0.5F, -3F, 2, 1, 6);
    ModelRenderer RightBackFin1 = new ModelRenderer(this, 31, 92);
    RightBackFin1.addBox(-2F, -1F, -2.5F, 2, 2, 5);
    ModelRenderer RightBackFin2 = new ModelRenderer(this, 3, 80);
    RightBackFin2.addBox(-10F, -0.5F, -3.5F, 8, 1, 7);
  
  //  TailPiece3.addChild(TailPiece4);
    TailPiece2.addChild(TailPiece3);
    TailPiece1.addChild(TailPiece2);
  
  
  
    LeftBackFinPiece.addChild(LeftBackFin1);
    LeftBackFinPiece.addChild(LeftBackFin3);
    LeftBackFinPiece.addChild(LeftBackFin2);
    RightFrontFinPiece.addChild(RightFrontFin3);
    RightFrontFinPiece.addChild(RightFrontFin1);
    RightFrontFinPiece.addChild(RightFrontFin2);
   LeftFrontFinPiece.addChild(LeftFrontFin1);
   LeftFrontFinPiece.addChild(LeftFrontFin3);
   LeftFrontFinPiece.addChild(LeftFrontFin2);
   HeadPiece.addChild(Head);
   HeadPiece.addChild(JawsTip);
   HeadPiece.addChild(Jaws);
  TailPiece1.addChild(Tail1);
  TailPiece2.addChild(Tail2);
  TailPiece3.addChild(Tail3);
  TailPiece3.addChild(TailFin);
  TailPiece3.addChild(Tail4);
  RightBackFinPiece.addChild(RightBackFin3);
  RightBackFinPiece.addChild(RightBackFin1);
  RightBackFinPiece.addChild(RightBackFin2);
  
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    LeftBackFinPiece.render(f5);
    RightFrontFinPiece.render(f5);
    LeftFrontFinPiece.render(f5);
    Neck.render(f5);
    Body2.render(f5);
    Body1.render(f5);
    HeadPiece.render(f5);
    TailPiece1.render(f5);
    RightBackFinPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    HeadPiece.rotateAngleY = f3 / 57.29578F;
	  HeadPiece.rotateAngleX = f4 / 57.29578F;
	  this.TailPiece1.rotateAngleY = MathHelper.cos(f * 0.6662F) * 0.5F * f1;
  }

}
