// Date: 12/10/2014 9:16:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelCompsognathus extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer RightArmUpper;
    ModelRenderer RightArmLower;
    ModelRenderer LeftArmUpper;
    ModelRenderer LeftArmLower;
    ModelRenderer RightLegPiece;
    ModelRenderer LeftLegPiece;
    ModelRenderer HeadPiece;
    ModelRenderer TailPiece1;
  ModelRenderer RightFoot;
  ModelRenderer RightLeg;
  ModelRenderer RightThigh;
  ModelRenderer LeftLeg2;
  ModelRenderer LeftLeg1;
  ModelRenderer LeftFoot;
  ModelRenderer Head;
  ModelRenderer Snout;
  ModelRenderer SnoutTip;
  ModelRenderer Crest;
  ModelRenderer Tail1;
  ModelRenderer Tail2;
  ModelRenderer TailPiece2;
 ModelRenderer TailPiece3;
 ModelRenderer Tail3;
  ModelRenderer TailPiece4;
  ModelRenderer Tail4;
  ModelRenderer TailPiece5;
  ModelRenderer Tail5;
  
  
  public ModelCompsognathus()
  {
    textureWidth = 100;
    textureHeight = 100;
    
      Body = new ModelRenderer(this, 56, 79);
      Body.addBox(0F, 0F, 0F, 6, 7, 14);
      Body.setRotationPoint(-2.5F, 6F, -8F);
      Body.setTextureSize(100, 100);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 52, 75);
      Neck1.addBox(-2.5F, -3F, -5F, 4, 5, 5);
      Neck1.setRotationPoint(1F, 11F, -5F);
      Neck1.setTextureSize(100, 100);
      Neck1.mirror = true;
      setRotation(Neck1, -0.4712389F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 43, 86);
      Neck2.addBox(-1.5F, -10F, -2F, 2, 10, 4);
      Neck2.setRotationPoint(1F, 9F, -8F);
      Neck2.setTextureSize(100, 100);
      Neck2.mirror = true;
      setRotation(Neck2, 0.837758F, 0F, 0F);
      RightArmUpper = new ModelRenderer(this, 75, 65);
      RightArmUpper.addBox(-1F, 0F, -1F, 1, 3, 2);
      RightArmUpper.setRotationPoint(-2F, 11F, -7F);
      RightArmUpper.setTextureSize(100, 100);
      RightArmUpper.mirror = true;
      setRotation(RightArmUpper, 0.3316126F, 0F, 0F);
      RightArmLower = new ModelRenderer(this, 30, 36);
      RightArmLower.addBox(-1F, 3F, -4F, 1, 2, 5);
      RightArmLower.setRotationPoint(-2F, 11F, -7F);
      RightArmLower.setTextureSize(100, 100);
      RightArmLower.mirror = true;
      setRotation(RightArmLower, 0.3316126F, 0F, 0F);
      LeftArmUpper = new ModelRenderer(this, 75, 65);
      LeftArmUpper.addBox(0F, 0F, -1F, 1, 3, 2);
      LeftArmUpper.setRotationPoint(3F, 11F, -7F);
      LeftArmUpper.setTextureSize(100, 100);
      LeftArmUpper.mirror = true;
      setRotation(LeftArmUpper, 0.3316126F, 0F, 0F);
      LeftArmLower = new ModelRenderer(this, 30, 36);
      LeftArmLower.addBox(1F, 3F, -4F, 1, 2, 5);
      LeftArmLower.setRotationPoint(2F, 11F, -7F);
      LeftArmLower.setTextureSize(100, 100);
      LeftArmLower.mirror = true;
      setRotation(LeftArmLower, 0.3316126F, 0F, 0F);
   
      
      RightLegPiece = new ModelRenderer(this, "RightLegPiece");
    RightLegPiece.setRotationPoint(-1F, 9F, 3F);
    setRotation(RightLegPiece, 0F, 0F, 0F);
    RightLegPiece.mirror = true;
     // RightLegPiece.addBox("RightFoot", -2.5F, 14F, -1F, 3, 1, 5);
     // RightLegPiece.addBox("RightLeg", -2F, 6F, 2F, 2, 8, 2);
    //  RightLegPiece.addBox("RightThigh", -2F, -1F, -3F, 2, 8, 6);
      ModelRenderer RightFoot = new ModelRenderer(this, 33, 78);
      RightFoot.addBox(-2.5F, 14F, -1F, 3, 1, 5);
      ModelRenderer RightLeg = new ModelRenderer(this, 34, 85);
      RightLeg.addBox(-2F, 6F, 2F, 2, 8, 2);
      ModelRenderer RightThigh = new ModelRenderer(this, 45, 60);
      RightThigh.addBox(-2F, -1F, -3F, 2, 8, 6);
      
      //    modelCompy.addChildModelRenderer(RightLegPiece);
    LeftLegPiece = new ModelRenderer(this, "LeftLegPiece");
    LeftLegPiece.setRotationPoint(2F, 9F, 3F);
    setRotation(LeftLegPiece, 0F, 0F, 0F);
    LeftLegPiece.mirror = true;
    //  LeftLegPiece.addBox("LeftLeg2", 0F, 6F, 2F, 2, 8, 2);
    //  LeftLegPiece.addBox("LeftLeg1", 0F, -1F, -3F, 2, 8, 6);
     // LeftLegPiece.addBox("LeftFoot", -0.5F, 14F, -1F, 3, 1, 5);
    ModelRenderer LeftLeg2 = new ModelRenderer(this, 34, 85);
    LeftLeg2.addBox(0F, 6F, 2F, 2, 8, 2);
    ModelRenderer LeftLeg1 = new ModelRenderer(this, 26, 63);
    LeftLeg1.addBox(0F, -1F, -3F, 2, 8, 6);  
    ModelRenderer LeftFoot = new ModelRenderer(this, 33, 78);
    LeftFoot.addBox(-0.5F, 14F, -1F, 3, 1, 5);
      
      //   modelCompy.addChildModelRenderer(LeftLegPiece);
    HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0.5F, 2F, -15F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
    //  HeadPiece.addBox("Head", -1.5F, -2F, -5F, 3, 4, 6);
   //   HeadPiece.addBox("Snout", -1F, -2F, -7F, 2, 4, 2);
   //   HeadPiece.addBox("SnoutTip", -1F, -1F, -10F, 2, 3, 3);
   //   HeadPiece.addBox("Crest", 0F, -5F, -5F, 0, 4, 7);
    ModelRenderer Head = new ModelRenderer(this, 0, 90);
    Head.addBox(-1.5F, -2F, -5F, 3, 4, 6);
    ModelRenderer Snout = new ModelRenderer(this, 20, 80);
    Snout.addBox(-1F, -2F, -7F, 2, 4, 2);
    ModelRenderer SnoutTip = new ModelRenderer(this, 9, 79);
    SnoutTip.addBox(-1F, -1F, -10F, 2, 3, 3);
    ModelRenderer Crest = new ModelRenderer(this, 25, -7);
    Crest.addBox(0F, -5F, -5F, 0, 4, 7);
   
    
    //   modelCompy.addChildModelRenderer(HeadPiece);
    TailPiece1 = new ModelRenderer(this, "TailPiece1");
    TailPiece1.setRotationPoint(0.5F, 8F, 6F);
    setRotation(TailPiece1, 0F, 0F, 0F);
    TailPiece1.mirror = true;
      //TailPiece1.addBox("Tail1", -2.5F, -2F, 0F, 5, 6, 4);
    ModelRenderer Tail1 = new ModelRenderer(this, 23, 51);
    Tail1.addBox(-2.5F, -2F, 0F, 5, 6, 4);
      
      
      TailPiece2 = new ModelRenderer(this, "TailPiece2");
    TailPiece2.setRotationPoint(0F, 0F, 4F);
    setRotation(TailPiece2, 0F, 0F, 0F);
    TailPiece2.mirror = true;
   //   TailPiece2.addBox("Tail2", -2F, -2F, 0F, 4, 5, 6);
    ModelRenderer Tail2 = new ModelRenderer(this, 2, 51);
    Tail2.addBox(-2F, -2F, 0F, 4, 5, 6);
      
      
      TailPiece3 = new ModelRenderer(this, "TailPiece3");
    TailPiece3.setRotationPoint(0F, 0F, 6F);
    setRotation(TailPiece3, 0F, 0F, 0F);
    TailPiece3.mirror = true;
    //  TailPiece3.addBox("Tail3", -1.5F, -2F, 0F, 3, 4, 8);
    ModelRenderer Tail3 = new ModelRenderer(this, 54, 47);
    Tail3.addBox(-1.5F, -2F, 0F, 3, 4, 8);
      
      
      TailPiece4 = new ModelRenderer(this, "TailPiece4");
    TailPiece4.setRotationPoint(0F, 0F, 8F);
    setRotation(TailPiece4, 0F, 0F, 0F);
    TailPiece4.mirror = true;
     // TailPiece4.addBox("Tail4", -1F, -2F, 0F, 2, 3, 10);
    ModelRenderer Tail4 = new ModelRenderer(this, 65, 6);
    Tail4.addBox(-1F, -2F, 0F, 2, 3, 10);
      
      
      TailPiece5 = new ModelRenderer(this, "TailPiece5");
    TailPiece5.setRotationPoint(0F, -1F, 10F);
    setRotation(TailPiece5, 0F, 0F, 0F);
    TailPiece5.mirror = true;
    //  TailPiece5.addBox("Tail5", 0F, -1F, 0F, 1, 2, 17);
    ModelRenderer Tail5 = new ModelRenderer(this, 38, 9);
    Tail5.addBox(0F, -1F, 0F, 1, 2, 17);
    
   
    
    RightLegPiece.addChild(RightFoot);
    RightLegPiece.addChild(RightLeg);
    RightLegPiece.addChild(RightThigh);
    LeftLegPiece.addChild(LeftLeg2);
    LeftLegPiece.addChild(LeftLeg1);
    LeftLegPiece.addChild(LeftFoot);
    HeadPiece.addChild(Head);
    HeadPiece.addChild(Snout);
    HeadPiece.addChild(SnoutTip);
    HeadPiece.addChild(Crest);
    TailPiece1.addChild(Tail1);
    TailPiece2.addChild(Tail2);
    TailPiece3.addChild(Tail3);
    TailPiece4.addChild(Tail4);
    TailPiece5.addChild(Tail5);
    
    
    TailPiece4.addChild(TailPiece5);
    TailPiece3.addChild(TailPiece4);
    TailPiece2.addChild(TailPiece3);
    TailPiece1.addChild(TailPiece2);
    //  TailPiece4.addChildModelRenderer(TailPiece5);
     // TailPiece3.addChildModelRenderer(TailPiece4);
     // TailPiece2.addChildModelRenderer(TailPiece3);
     // TailPiece1.addChildModelRenderer(TailPiece2);
    //  modelCompy.addChildModelRenderer(TailPiece1);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Body.render(f5);
    Neck1.render(f5);
    Neck2.render(f5);
    RightArmUpper.render(f5);
    RightArmLower.render(f5);
    LeftArmUpper.render(f5);
    LeftArmLower.render(f5);
    RightLegPiece.render(f5);
    LeftLegPiece.render(f5);
    HeadPiece.render(f5);
    TailPiece1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
    HeadPiece.rotateAngleY = f3 / 57.29578F;
	  HeadPiece.rotateAngleX = f4 / 57.29578F;
	  this.LeftLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	   this.RightLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
