// Date: 1/16/2015 5:30:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpinoSwim extends ModelBase
{
  //fields
    ModelRenderer LeftClaw;
    ModelRenderer Sail7;
    ModelRenderer LeftHand;
    ModelRenderer Sail6;
    ModelRenderer LeftArmLower;
    ModelRenderer Sail2;
    ModelRenderer Sail8;
    ModelRenderer LeftArmUpper;
    ModelRenderer Sail5;
    ModelRenderer Neck2;
    ModelRenderer Sail4;
    ModelRenderer Neck1;
    ModelRenderer Body;
    ModelRenderer Sail3;
    ModelRenderer RightArmUpper;
    ModelRenderer Sail1;
    ModelRenderer RightArmLower;
    ModelRenderer RightHand;
    ModelRenderer RightClaw;
    ModelRenderer TailPiece1;
    ModelRenderer LeftLegPiece;
    ModelRenderer HeadPiece;
    ModelRenderer RightLegPiece;
  ModelRenderer Tail1;
  ModelRenderer Sail9;
  ModelRenderer TailPiece2;
  ModelRenderer Tail2;
  ModelRenderer Sail11;
  ModelRenderer Sail10;
    ModelRenderer TailPiece3;
    ModelRenderer Tail3;
    ModelRenderer Sail12;
    ModelRenderer Sail13;
    ModelRenderer TailPiece4;
    ModelRenderer Tail4;
    ModelRenderer TailPiece5;
    ModelRenderer Tail5;
    ModelRenderer TailPiece6;
    ModelRenderer Tail6;
    ModelRenderer TailPiece7;
    ModelRenderer Tail7;
    ModelRenderer LeftThigh;
    ModelRenderer LeftLeg;
    ModelRenderer LeftFoot;
    ModelRenderer Head;
    ModelRenderer Snout;
    ModelRenderer SnoutTip;
    ModelRenderer Bump;
    ModelRenderer Beard;
    ModelRenderer RightFoot;
    ModelRenderer RightLeg;
    ModelRenderer RightThigh;
    
    public ModelSpinoSwim()
  {
    textureWidth = 200;
    textureHeight = 200;
    
      LeftClaw = new ModelRenderer(this, 156, 37);
      LeftClaw.addBox(0F, 9F, -9F, 2, 1, 5);
      LeftClaw.setRotationPoint(5F, 21F, -17F);
      LeftClaw.setTextureSize(200, 200);
      LeftClaw.mirror = true;
      setRotation(LeftClaw, 0.5235988F, 0.1570796F, 0F);
      Sail7 = new ModelRenderer(this, 115, 175);
      Sail7.addBox(0F, 0F, 0F, 3, 18, 4);
      Sail7.setRotationPoint(-1.5F, -9F, 5F);
      Sail7.setTextureSize(200, 200);
      Sail7.mirror = true;
      setRotation(Sail7, 0F, 0F, 0F);
      LeftHand = new ModelRenderer(this, 66, 141);
      LeftHand.addBox(0F, 8F, -9F, 1, 3, 4);
      LeftHand.setRotationPoint(5F, 21F, -17F);
      LeftHand.setTextureSize(200, 200);
      LeftHand.mirror = true;
      setRotation(LeftHand, 0.6981317F, 0.1570796F, 0F);
      Sail6 = new ModelRenderer(this, 99, 174);
      Sail6.addBox(0F, 0F, 0F, 3, 16, 3);
      Sail6.setRotationPoint(-1.5F, -7F, 2F);
      Sail6.setTextureSize(200, 200);
      Sail6.mirror = true;
      setRotation(Sail6, 0F, 0F, 0F);
      LeftArmLower = new ModelRenderer(this, 18, 116);
      LeftArmLower.addBox(-1F, 8F, -5F, 2, 3, 8);
      LeftArmLower.setRotationPoint(5F, 21F, -17F);
      LeftArmLower.setTextureSize(200, 200);
      LeftArmLower.mirror = true;
      setRotation(LeftArmLower, 0.6981317F, 0F, 0F);
      Sail2 = new ModelRenderer(this, 20, 178);
      Sail2.addBox(0F, 0F, 0F, 2, 12, 3);
      Sail2.setRotationPoint(-1F, -3F, -16F);
      Sail2.setTextureSize(200, 200);
      Sail2.mirror = true;
      setRotation(Sail2, 0F, 0F, 0F);
      Sail8 = new ModelRenderer(this, 135, 176);
      Sail8.addBox(0F, 0F, 0F, 3, 16, 5);
      Sail8.setRotationPoint(-1.5F, -7F, 9F);
      Sail8.setTextureSize(200, 200);
      Sail8.mirror = true;
      setRotation(Sail8, 0F, 0F, 0F);
      LeftArmUpper = new ModelRenderer(this, 7, 96);
      LeftArmUpper.addBox(-2F, 0F, 0F, 3, 8, 4);
      LeftArmUpper.setRotationPoint(5F, 21F, -17F);
      LeftArmUpper.setTextureSize(200, 200);
      LeftArmUpper.mirror = true;
      setRotation(LeftArmUpper, 0.6981317F, 0F, 0F);
      Sail5 = new ModelRenderer(this, 74, 170);
      Sail5.addBox(0.5F, 0F, 0F, 3, 15, 7);
      Sail5.setRotationPoint(-2F, -6F, -5F);
      Sail5.setTextureSize(200, 200);
      Sail5.mirror = true;
      setRotation(Sail5, 0F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 156, 3);
      Neck2.addBox(-2F, -2F, -14F, 4, 8, 15);
      Neck2.setRotationPoint(0F, 14F, -20F);
      Neck2.setTextureSize(200, 200);
      Neck2.mirror = true;
      setRotation(Neck2, 0F, 0F, 0F);
      Sail4 = new ModelRenderer(this, 55, 170);
      Sail4.addBox(0F, 0F, 0F, 3, 16, 4);
      Sail4.setRotationPoint(-1.5F, -7F, -9F);
      Sail4.setTextureSize(200, 200);
      Sail4.mirror = true;
      setRotation(Sail4, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 102, 96);
      Neck1.addBox(-3.5F, -4F, -4F, 7, 11, 6);
      Neck1.setRotationPoint(0F, 15F, -18F);
      Neck1.setTextureSize(200, 200);
      Neck1.mirror = true;
      setRotation(Neck1, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 13, 47);
      Body.addBox(7F, -3F, -2F, 10, 15, 32);
      Body.setRotationPoint(-12F, 12F, -16F);
      Body.setTextureSize(200, 200);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Sail3 = new ModelRenderer(this, 35, 174);
      Sail3.addBox(0F, 0F, 0F, 3, 15, 4);
      Sail3.setRotationPoint(-1.5F, -6F, -13F);
      Sail3.setTextureSize(200, 200);
      Sail3.mirror = true;
      setRotation(Sail3, 0F, 0F, 0F);
      RightArmUpper = new ModelRenderer(this, 7, 96);
      RightArmUpper.addBox(-1F, 0F, 0F, 3, 8, 4);
      RightArmUpper.setRotationPoint(-5F, 21F, -17F);
      RightArmUpper.setTextureSize(200, 200);
      RightArmUpper.mirror = true;
      setRotation(RightArmUpper, 0.6981317F, 0F, 0F);
      Sail1 = new ModelRenderer(this, 6, 183);
      Sail1.addBox(0F, 0F, 0F, 1, 8, 3);
      Sail1.setRotationPoint(-0.5F, 4F, -19F);
      Sail1.setTextureSize(200, 200);
      Sail1.mirror = true;
      setRotation(Sail1, 0F, 0F, 0F);
      RightArmLower = new ModelRenderer(this, 18, 116);
      RightArmLower.addBox(-1F, 8F, -5F, 2, 3, 8);
      RightArmLower.setRotationPoint(-5F, 21F, -17F);
      RightArmLower.setTextureSize(200, 200);
      RightArmLower.mirror = true;
      setRotation(RightArmLower, 0.6981317F, 0F, 0F);
      RightHand = new ModelRenderer(this, 66, 141);
      RightHand.addBox(-1F, 8F, -9F, 1, 3, 4);
      RightHand.setRotationPoint(-5F, 21F, -17F);
      RightHand.setTextureSize(200, 200);
      RightHand.mirror = true;
      setRotation(RightHand, 0.6981317F, -0.1570796F, 0F);
      RightClaw = new ModelRenderer(this, 132, 37);
      RightClaw.addBox(-2F, 9F, -9F, 2, 1, 5);
      RightClaw.setRotationPoint(-5F, 21F, -17F);
      RightClaw.setTextureSize(200, 200);
      RightClaw.mirror = true;
      setRotation(RightClaw, 0.5235988F, -0.1570796F, 0F);
   
      
      TailPiece1 = new ModelRenderer(this, "TailPiece1");
    TailPiece1.setRotationPoint(0F, 14F, 14F);
    setRotation(TailPiece1, 0F, 0F, 0F);
    TailPiece1.mirror = true;
     // TailPiece1.addBox("Tail1", -4.5F, -5F, 0F, 9, 13, 5);
      //TailPiece1.addBox("Sail9", -1.5F, -19F, 0F, 3, 14, 5);
    ModelRenderer Tail1 = new ModelRenderer(this, 68, 112);
    Tail1.addBox(-4.5F, -5F, 0F, 9, 13, 5);
    ModelRenderer Sail9 = new ModelRenderer(this, 156, 170);
    Sail9.addBox(-1.5F, -19F, 0F, 3, 14, 5);
      
      
      TailPiece2 = new ModelRenderer(this, "TailPiece2");
    TailPiece2.setRotationPoint(0F, 1F, 5F);
    setRotation(TailPiece2, 0F, 0F, 0F);
    TailPiece2.mirror = true;
     // TailPiece2.addBox("Tail2", -4F, -5F, 0F, 8, 11, 8);
      //TailPiece2.addBox("Sail11", -1F, -14F, 4F, 2, 9, 4);
      //TailPiece2.addBox("Sail10", -1F, -17F, 0F, 2, 12, 4);
    ModelRenderer Tail2 = new ModelRenderer(this, 156, 89);
    Tail2.addBox(-4F, -5F, 0F, 8, 11, 8);
    ModelRenderer Sail11 = new ModelRenderer(this, 13, 160);
    Sail11.addBox(-1F, -14F, 4F, 2, 9, 4);
    ModelRenderer Sail10 = new ModelRenderer(this, 176, 170);
    Sail10.addBox(-1F, -17F, 0F, 2, 12, 4);
      
      
      TailPiece3 = new ModelRenderer(this, "TailPiece3");
    TailPiece3.setRotationPoint(0F, 0F, 8F);
    setRotation(TailPiece3, 0F, 0F, 0F);
    TailPiece3.mirror = true;
     // TailPiece3.addBox("Tail3", -3F, -4F, 0F, 6, 9, 19);
     // TailPiece3.addBox("Sail12", -0.5F, -11F, 0F, 1, 7, 4);
    //  TailPiece3.addBox("Sail13", -0.5F, -8F, 4F, 1, 4, 4);
    ModelRenderer Tail3 = new ModelRenderer(this, 124, 105);
    Tail3.addBox(-3F, -4F, 0F, 6, 9, 19);
    ModelRenderer Sail12 = new ModelRenderer(this, 30, 159);
    Sail12.addBox(-0.5F, -11F, 0F, 1, 7, 4);
    ModelRenderer Sail13 = new ModelRenderer(this, 44, 160);
    Sail13.addBox(-0.5F, -8F, 4F, 1, 4, 4);
     
    
    TailPiece4 = new ModelRenderer(this, "TailPiece4");
    TailPiece4.setRotationPoint(0F, 0F, 19F);
    setRotation(TailPiece4, 0F, 0F, 0F);
    TailPiece4.mirror = true;
  //    TailPiece4.addBox("Tail4", -2.5F, -3F, 0F, 5, 7, 20);
    ModelRenderer Tail4 = new ModelRenderer(this, 63, 139);
    Tail4.addBox(-2.5F, -3F, 0F, 5, 7, 20);
      
      
      TailPiece5 = new ModelRenderer(this, "TailPiece5");
    TailPiece5.setRotationPoint(0F, -0.5F, 20F);
    setRotation(TailPiece5, 0F, 0F, 0F);
    TailPiece5.mirror = true;
     // TailPiece5.addBox("Tail5", -2F, -2F, 0F, 4, 6, 13);
    ModelRenderer Tail5 = new ModelRenderer(this, 120, 134);
    Tail5.addBox(-2F, -2F, 0F, 4, 6, 13);
      
      
      
      TailPiece6 = new ModelRenderer(this, "TailPiece6");
    TailPiece6.setRotationPoint(0F, 0.5F, 13F);
    setRotation(TailPiece6, 0F, 0F, 0F);
    TailPiece6.mirror = true;
  //    TailPiece6.addBox("Tail6", -1.5F, -2F, 0F, 3, 5, 13);
    ModelRenderer Tail6 = new ModelRenderer(this, 116, 153);
    Tail6.addBox(-1.5F, -2F, 0F, 3, 5, 13);
      
      
      TailPiece7 = new ModelRenderer(this, "TailPiece7");
    TailPiece7.setRotationPoint(0F, 0.5F, 13F);
    setRotation(TailPiece7, 0F, 0F, 0F);
    TailPiece7.mirror = true;
    //  TailPiece7.addBox("Tail7", -1F, -2F, 0F, 2, 4, 10);
    ModelRenderer Tail7 = new ModelRenderer(this, 156, 134);
    Tail7.addBox(-1F, -2F, 0F, 2, 4, 10);
    
    
    //   TailPiece6.addChildModelRenderer(TailPiece7);
    //  TailPiece5.addChildModelRenderer(TailPiece6);
    //  TailPiece4.addChildModelRenderer(TailPiece5);
   //   TailPiece3.addChildModelRenderer(TailPiece4);
   //   TailPiece2.addChildModelRenderer(TailPiece3);
   //   TailPiece1.addChildModelRenderer(TailPiece2);
   //   modelSpino.addChildModelRenderer(TailPiece1);
   
      
      
      
      LeftLegPiece = new ModelRenderer(this, "LeftLegPiece");
    LeftLegPiece.setRotationPoint(3F, 17F, 8F);
    setRotation(LeftLegPiece, 0F, 0F, 0F);
    LeftLegPiece.mirror = true;
    //  LeftLegPiece.addBox("LeftThigh", 0F, -2F, -4F, 4, 13, 9);
 //     LeftLeg.mirror = true;
    //  LeftLegPiece.addBox("LeftLeg", 0.5F, 10F, 2F, 3, 7, 4);
     // LeftLeg.mirror = false;
     // LeftFoot.mirror = true;
     // LeftLegPiece.addBox("LeftFoot", 0F, 16F, 2F, 4, 8, 3);
     // LeftFoot.mirror = false;
     // modelSpino.addChildModelRenderer(LeftLegPiece);
      ModelRenderer LeftThigh = new ModelRenderer(this, 134, 60);
      LeftThigh.addBox(0F, -2F, -4F, 4, 13, 9);
      ModelRenderer LeftLeg = new ModelRenderer(this, 38, 99);
      LeftLeg.addBox(0.5F, 10F, 2F, 3, 7, 4);
      ModelRenderer LeftFoot = new ModelRenderer(this, 4, 129);
      LeftFoot.addBox(0F, 16F, 2F, 4, 8, 3);
    
      
      HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0.5F, 15F, -34F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
    //  HeadPiece.addBox("Head", -3F, -3F, -12F, 5, 8, 12);
    //  HeadPiece.addBox("Snout", -2.5F, -2F, -21F, 4, 6, 9);
    //  HeadPiece.addBox("SnoutTip", -2.5F, -1.5F, -29F, 4, 5, 8);
     // HeadPiece.addBox("Bump", -1F, -4F, -15F, 1, 2, 4);
     // HeadPiece.addBox("Beard", -0.5F, 2F, -20F, 0, 7, 17);
     // modelSpino.addChildModelRenderer(HeadPiece);
    ModelRenderer Head = new ModelRenderer(this, 39, 25);
    Head.addBox(-3F, -3F, -12F, 5, 8, 12);
    ModelRenderer Snout = new ModelRenderer(this, 85, 31);
    Snout.addBox(-2.5F, -2F, -21F, 4, 6, 9);
    ModelRenderer SnoutTip = new ModelRenderer(this, 66, 22);
    SnoutTip.addBox(-2.5F, -1.5F, -29F, 4, 5, 8);
    ModelRenderer Bump = new ModelRenderer(this, 38, 28);
    Bump.addBox(-1F, -4F, -15F, 1, 2, 4);
    ModelRenderer Beard = new ModelRenderer(this, 0, 10);
    Beard.addBox(-0.5F, 2F, -20F, 0, 7, 17);
   
    
    RightLegPiece = new ModelRenderer(this, "RightLegPiece");
    RightLegPiece.setRotationPoint(-3F, 17F, 8F);
    setRotation(RightLegPiece, 0F, 0F, 0F);
    RightLegPiece.mirror = true;
    //  RightLegPiece.addBox("RightFoot", -4F, 16F, 2F, 4, 8, 3);
    //  RightLegPiece.addBox("RightLeg", -3.5F, 10F, 2F, 3, 7, 4);
     // RightLegPiece.addBox("RightThigh", -4F, -2F, -4F, 4, 13, 9);
   //   modelSpino.addChildModelRenderer(RightLegPiece);
    ModelRenderer RightFoot = new ModelRenderer(this, 4, 129);
    RightFoot.addBox(-4F, 16F, 2F, 4, 8, 3);
    ModelRenderer RightLeg = new ModelRenderer(this, 38, 99);
    RightLeg.addBox(-3.5F, 10F, 2F, 3, 7, 4);
    ModelRenderer RightThigh = new ModelRenderer(this, 104, 60);
    RightThigh.addBox(-4F, -2F, -4F, 4, 13, 9);
  
    TailPiece6.addChild(TailPiece7);
    TailPiece5.addChild(TailPiece6);
    TailPiece4.addChild(TailPiece5);
    TailPiece3.addChild(TailPiece4);
    TailPiece2.addChild(TailPiece3);
    TailPiece1.addChild(TailPiece2);
  
  
    TailPiece1.addChild(Tail1);
    TailPiece1.addChild(Sail9);
    TailPiece2.addChild(Tail2);
    TailPiece2.addChild(Sail11);
    TailPiece2.addChild(Sail10);
    TailPiece3.addChild(Tail3);
    TailPiece3.addChild(Sail12);
    TailPiece3.addChild(Sail13);
    TailPiece4.addChild(Tail4);
    TailPiece5.addChild(Tail5);
    TailPiece6.addChild(Tail6);
    TailPiece7.addChild(Tail7);
    LeftLegPiece.addChild(LeftThigh);
    LeftLegPiece.addChild(LeftLeg);
    LeftLegPiece.addChild(LeftFoot);
    HeadPiece.addChild(Head);
    HeadPiece.addChild(Snout);
    HeadPiece.addChild(SnoutTip);
    HeadPiece.addChild(Bump);
    HeadPiece.addChild(Beard);
    RightLegPiece.addChild(RightFoot);
    RightLegPiece.addChild(RightLeg);
    RightLegPiece.addChild(RightThigh);
  
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    LeftClaw.render(f5);
    Sail7.render(f5);
    LeftHand.render(f5);
    Sail6.render(f5);
    LeftArmLower.render(f5);
    Sail2.render(f5);
    Sail8.render(f5);
    LeftArmUpper.render(f5);
    Sail5.render(f5);
    Neck2.render(f5);
    Sail4.render(f5);
    Neck1.render(f5);
    Body.render(f5);
    Sail3.render(f5);
    RightArmUpper.render(f5);
    Sail1.render(f5);
    RightArmLower.render(f5);
    RightHand.render(f5);
    RightClaw.render(f5);
    TailPiece1.render(f5);
    LeftLegPiece.render(f5);
    HeadPiece.render(f5);
    RightLegPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
