// Date: 12/28/2014 10:43:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelQuetzLand extends ModelBase
{
  //fields
    ModelRenderer Tail;
    ModelRenderer LowerBody;
    ModelRenderer UpperBody;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer TailTip;
    ModelRenderer LeftLegPiece;
    ModelRenderer RightLegPiece;
    ModelRenderer HeadPiece;
    ModelRenderer RightWingPiece;
    ModelRenderer LeftWingPiece;
  ModelRenderer LeftLeg2;
  ModelRenderer LeftLeg;
    ModelRenderer LeftFoot;
    ModelRenderer RightLeg1;
    ModelRenderer RightLeg2;
    ModelRenderer RightFoot;
    ModelRenderer Head;
    ModelRenderer Crest;
    ModelRenderer Beak1;
    ModelRenderer Beak2;
    ModelRenderer Beak3;
    ModelRenderer RightArm1;
    ModelRenderer RightArm2;
    ModelRenderer RightArm3;
    ModelRenderer RightHand;
    ModelRenderer RightWing1;
    ModelRenderer RightWingPiece2;
    ModelRenderer RightWing2;
    ModelRenderer RightArm4;
    ModelRenderer LeftArm1;
    ModelRenderer LeftArm2;
    ModelRenderer LeftArm3;
    ModelRenderer LeftHand;
    ModelRenderer LeftWing1;
    ModelRenderer LeftWingPiece2;
    ModelRenderer LeftArm4;
    ModelRenderer LeftWing2;
    
  public ModelQuetzLand()
  {
    textureWidth = 500;
    textureHeight = 150;
    
      Tail = new ModelRenderer(this, 3, 93);
      Tail.addBox(0F, -2F, 0F, 3, 2, 5);
      Tail.setRotationPoint(-1.5F, 1.5F, 11F);
      Tail.setTextureSize(500, 150);
      Tail.mirror = true;
      setRotation(Tail, -0.9773844F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 108, 104);
      LowerBody.addBox(-4.5F, -2F, 11F, 9, 7, 7);
      LowerBody.setRotationPoint(0F, -10F, -2F);
      LowerBody.setTextureSize(500, 150);
      LowerBody.mirror = true;
      setRotation(LowerBody, -0.6981317F, 0F, 0F);
      UpperBody = new ModelRenderer(this, 95, 81);
      UpperBody.addBox(-5F, 0F, 6F, 10, 8, 11);
      UpperBody.setRotationPoint(0F, -16F, -5F);
      UpperBody.setTextureSize(500, 150);
      UpperBody.mirror = true;
      setRotation(UpperBody, -0.6981317F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 1, 73);
      Neck1.addBox(-2.5F, -5F, -11F, 5, 7, 10);
      Neck1.setRotationPoint(0F, -7F, -3F);
      Neck1.setTextureSize(500, 150);
      Neck1.mirror = true;
      setRotation(Neck1, -0.7853982F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 28, 73);
      Neck2.addBox(-2F, -4F, -33F, 4, 7, 23);
      Neck2.setRotationPoint(0F, -7F, -3F);
      Neck2.setTextureSize(500, 150);
      Neck2.mirror = true;
      setRotation(Neck2, -0.8901179F, 0F, 0F);
      TailTip = new ModelRenderer(this, 3, 104);
      TailTip.addBox(0F, -3F, 4F, 2, 2, 3);
      TailTip.setRotationPoint(-1F, 1.5F, 11F);
      TailTip.setTextureSize(500, 150);
      TailTip.mirror = true;
      setRotation(TailTip, -1.239184F, 0F, 0F);
    LeftLegPiece = new ModelRenderer(this, "LeftLegPiece");
    LeftLegPiece.setRotationPoint(3F, 1F, 9F);
    setRotation(LeftLegPiece, 0F, 0F, 0F);
    LeftLegPiece.mirror = true;
   //   LeftLeg2.mirror = true;
    //  LeftLegPiece.addBox("LeftLeg2", 0.5F, 8F, -1F, 2, 14, 3);
    //  LeftLeg2.mirror = false;
   //   LeftLegPiece.addBox("LeftLeg1", 0F, -2F, -2F, 3, 10, 5);
  //    LeftLegPiece.addBox("LeftFoot", 0F, 22F, -2F, 3, 1, 4);
  //    modelQuetz.addChildModelRenderer(LeftLegPiece);
      ModelRenderer LeftLeg2 = new ModelRenderer(this, 363, 111);
      LeftLeg2.addBox(0.5F, 8F, -1F, 2, 14, 3);
      ModelRenderer LeftLeg1 = new ModelRenderer(this, 318, 58);
      LeftLeg1.addBox(0F, -2F, -2F, 3, 10, 5);
      ModelRenderer LeftFoot = new ModelRenderer(this, 237, 79);
      LeftFoot.addBox(0F, 22F, -2F, 3, 1, 4);
      
      
      
      
      RightLegPiece = new ModelRenderer(this, "RightLegPiece");
    RightLegPiece.setRotationPoint(-3F, 1F, 9F);
    setRotation(RightLegPiece, 0F, 0F, 0F);
    RightLegPiece.mirror = true;
      //RightLeg1.mirror = true;
     // RightLegPiece.addBox("RightLeg1", -3F, -2F, -2F, 3, 10, 5);
     // RightLeg1.mirror = false;
      //RightLegPiece.addBox("RightLeg2", -2.5F, 8F, -1F, 2, 14, 3);
     // RightLegPiece.addBox("RightFoot", -3F, 22F, -2F, 3, 1, 4);
     // modelQuetz.addChildModelRenderer(RightLegPiece);
      ModelRenderer RightLeg1 = new ModelRenderer(this, 320, 58);
      RightLeg1.addBox(-3F, -2F, -2F, 3, 10, 5);
      ModelRenderer RightLeg2 = new ModelRenderer(this, 363, 111);
      RightLeg2.addBox(-2.5F, 8F, -1F, 2, 14, 3);
      ModelRenderer RightFoot = new ModelRenderer(this, 237, 79);
      RightFoot.addBox(-3F, 22F, -2F, 3, 1, 4);
      
      
      
      
      
      HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0F, -33F, -21F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
   //   HeadPiece.addBox("Head", -2.5F, -3.5F, -11F, 5, 8, 11);
    //  HeadPiece.addBox("Crest", 0F, -9F, -13F, 0, 7, 16);
    //  HeadPiece.addBox("Beak1", -2F, -2.5F, -21F, 4, 7, 10);
    //  HeadPiece.addBox("Beak2", -1.5F, -1.5F, -39F, 3, 5, 9);
    //  HeadPiece.addBox("Beak3", -1.5F, -2F, -30F, 3, 6, 9);
     // modelQuetz.addChildModelRenderer(HeadPiece);
    ModelRenderer Head = new ModelRenderer(this, 4, 103);
    Head.addBox(-2.5F, -3.5F, -11F, 5, 8, 11);
    ModelRenderer Crest = new ModelRenderer(this, 66, 66);
    Crest.addBox(0F, -9F, -13F, 0, 7, 16);
    ModelRenderer Beak1 = new ModelRenderer(this, 43, 106);
    Beak1.addBox(-2F, -2.5F, -21F, 4, 7, 10);
    ModelRenderer Beak2 = new ModelRenderer(this, 96, 118);
    Beak2.addBox(-1.5F, -1.5F, -39F, 3, 5, 9);
    ModelRenderer Beak3 = new ModelRenderer(this, 78, 103);
    Beak3.addBox(-1.5F, -2F, -30F, 3, 6, 9);
    
    
    
    
    
    RightWingPiece = new ModelRenderer(this, "RightWingPiece");
    RightWingPiece.setRotationPoint(-3F, -7F, -1F);
    setRotation(RightWingPiece, 0F, 0F, 0F);
    RightWingPiece.mirror = true;
    //  RightWingPiece.addBox("RightArm1", -4F, -2F, -2F, 4, 8, 5);
     // RightWingPiece.addBox("RightArm2", -3F, 6F, -2F, 3, 12, 4);
     // RightWingPiece.addBox("RightArm3", -3F, 18F, -2F, 3, 13, 3);
    //  RightWingPiece.addBox("RightHand", -3F, 30F, -5F, 3, 1, 3);
    //  RightWingPiece.addBox("RightWing1", -2F, -2F, 1F, 0, 33, 8);
    ModelRenderer RightArm1 = new ModelRenderer(this, 203, 112);
    RightArm1.addBox(-4F, -2F, -2F, 4, 8, 5);
    ModelRenderer RightArm2 = new ModelRenderer(this, 230, 105);
    RightArm2.addBox(-3F, 6F, -2F, 3, 12, 4);
    ModelRenderer RightArm3 = new ModelRenderer(this, 255, 99);
    RightArm3.addBox(-3F, 18F, -2F, 3, 13, 3);
    ModelRenderer RightHand = new ModelRenderer(this, 18, 145);
    RightHand.addBox(-3F, 30F, -5F, 3, 1, 3);
    ModelRenderer RightWing1 = new ModelRenderer(this, 291, 105);
    RightWing1.addBox(-2F, -2F, 1F, 0, 33, 8);
      
    
    
    
    RightWingPiece2 = new ModelRenderer(this, "RightWingPiece2");
    RightWingPiece2.setRotationPoint(-2F, 30F, -1F);
    setRotation(RightWingPiece2, 0F, 0F, 45F);
    RightWingPiece2.mirror = true;
    //  RightWingPiece2.addBox("RightWing2", -30F, 0F, 1F, 30, 1, 8);
    //  RightWingPiece2.addBox("RightArm4", -30F, -1F, -1F, 30, 2, 2);
     // RightWingPiece.addChildModelRenderer(RightWingPiece2);
    //  modelQuetz.addChildModelRenderer(RightWingPiece);
    ModelRenderer RightWing2 = new ModelRenderer(this, 358, 35);
    RightWing2.addBox(-30F, 0F, 1F, 30, 1, 8);
    ModelRenderer RightArm4 = new ModelRenderer(this, 52, 134);
    RightArm4.addBox(-30F, -1F, -1F, 30, 2, 2);
      
      
      LeftWingPiece = new ModelRenderer(this, "LeftWingPiece");
    LeftWingPiece.setRotationPoint(3F, -7F, -1F);
    setRotation(LeftWingPiece, 0F, 0F, 0F);
    LeftWingPiece.mirror = true;
    //  LeftWingPiece.addBox("LeftArm1", 0F, -2F, -2F, 4, 8, 5);
   //   LeftWingPiece.addBox("LeftArm2", 0F, 6F, -2F, 3, 12, 4);
   //   LeftWingPiece.addBox("LeftArm3", 0F, 18F, -2F, 3, 13, 3);
   //   LeftWingPiece.addBox("LeftHand", 0F, 30F, -5F, 3, 1, 3);
   //   LeftWingPiece.addBox("LeftWing1", 2F, 1F, 1F, 0, 33, 8);
    ModelRenderer LeftArm1 = new ModelRenderer(this, 453, 112);
    LeftArm1.addBox(0F, -2F, -2F, 4, 8, 5);
    ModelRenderer LeftArm2 = new ModelRenderer(this, 429, 108);
    LeftArm2.addBox(0F, 6F, -2F, 3, 12, 4);
    ModelRenderer LeftArm3 = new ModelRenderer(this, 406, 99);
    LeftArm3.addBox(0F, 18F, -2F, 3, 13, 3);
    ModelRenderer LeftHand = new ModelRenderer(this, 18, 145);
    LeftHand.addBox(0F, 30F, -5F, 3, 1, 3);
    ModelRenderer LeftWing1 = new ModelRenderer(this, 291, 108);
    LeftWing1.addBox(2F, 1F, 1F, 0, 33, 8);
      
    
    
    LeftWingPiece2 = new ModelRenderer(this, "LeftWingPiece2");
   LeftWingPiece2.setRotationPoint(2F, 30F, -1F);
    setRotation(LeftWingPiece2, 0F, 0F, -45F);
    LeftWingPiece2.mirror = true;
     // LeftWingPiece2.addBox("LeftWing2", 0F, 0F, 1F, 30, 1, 8);
     // LeftWingPiece2.addBox("LeftArm4", 0F, -1F, -1F, 30, 2, 2);
     // LeftWingPiece.addChildModelRenderer(LeftWingPiece2);
      //modelQuetz.addChildModelRenderer(LeftWingPiece);
    ModelRenderer LeftWing2 = new ModelRenderer(this, 361, 16);
    LeftWing2.addBox(0F, 0F, 1F, 30, 1, 8);
    ModelRenderer LeftArm4 = new ModelRenderer(this, 52, 134);
    LeftArm4.addBox(0F, -1F, -1F, 30, 2, 2);
  
  
  
    RightWingPiece.addChild(RightWingPiece2);
    LeftWingPiece.addChild(LeftWingPiece2);
  
 
    LeftLegPiece.addChild(LeftLeg2);
    LeftLegPiece.addChild(LeftLeg1);
    LeftLegPiece.addChild(LeftFoot);
    RightLegPiece.addChild(RightLeg1);
    RightLegPiece.addChild(RightLeg2);
    RightLegPiece.addChild(RightFoot);
    HeadPiece.addChild(Head);
    HeadPiece.addChild(Crest);
    HeadPiece.addChild(Beak1);
    HeadPiece.addChild(Beak2);
    HeadPiece.addChild(Beak3);
    RightWingPiece.addChild(RightArm1);
    RightWingPiece.addChild(RightArm2);
    RightWingPiece.addChild(RightArm3);
    RightWingPiece.addChild(RightHand);
    RightWingPiece.addChild(RightWing1);
    RightWingPiece2.addChild(RightWing2);
    RightWingPiece2.addChild(RightArm4);
    LeftWingPiece.addChild(LeftArm1);
    LeftWingPiece.addChild(LeftArm2);
    LeftWingPiece.addChild(LeftArm3);
    LeftWingPiece.addChild(LeftHand);
    LeftWingPiece.addChild(LeftWing1);
    LeftWingPiece2.addChild(LeftWing2);
    LeftWingPiece2.addChild(LeftArm4);
    
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Tail.render(f5);
    LowerBody.render(f5);
    UpperBody.render(f5);
    Neck1.render(f5);
    Neck2.render(f5);
    TailTip.render(f5);
    LeftLegPiece.render(f5);
    RightLegPiece.render(f5);
    HeadPiece.render(f5);
    RightWingPiece.render(f5);
    LeftWingPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,null);
    HeadPiece.rotateAngleY = f3 / 57.29578F;
	  HeadPiece.rotateAngleX = f4 / 57.29578F;
	  this.LeftLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	   this.RightLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  
  }

}
