// Date: 1/10/2015 4:16:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelMassospondylus extends ModelBase
{
  //fields
    ModelRenderer Neck2;
    ModelRenderer Neck1;
    ModelRenderer Body;
    ModelRenderer Chest;
    ModelRenderer RightArmUpper;
    ModelRenderer RightArmLower;
    ModelRenderer RightHand;
    ModelRenderer RightClaw;
    ModelRenderer LeftArmUpper;
    ModelRenderer LeftArmLower;
    ModelRenderer LeftHand;
    ModelRenderer LeftClaw;
    ModelRenderer Mane;
    ModelRenderer TailPiece1;
    ModelRenderer HeadPiece;
    ModelRenderer LeftLegPiece;
    ModelRenderer RightLegPiece;
  ModelRenderer Tail1;
 ModelRenderer TailPiece2;
 ModelRenderer Tail2;
 ModelRenderer TailPiece3;
 ModelRenderer Tail3;
  ModelRenderer TailPiece4;
  ModelRenderer Tail4;
  ModelRenderer TailPiece5;
  ModelRenderer Tail5;
  ModelRenderer Snout;
  ModelRenderer Head;
  ModelRenderer SnoutTip;
  ModelRenderer LeftThigh;
  ModelRenderer LeftLegLower;
  ModelRenderer LeftFoot;
  ModelRenderer RightThigh;
  ModelRenderer RightLegLower;
  ModelRenderer RightFoot;
  public ModelMassospondylus()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Neck2 = new ModelRenderer(this, 32, 1);
      Neck2.addBox(-2F, 0F, 0F, 3, 4, 18);
      Neck2.setRotationPoint(0.5F, -0.5F, -34F);
      Neck2.setTextureSize(128, 128);
      Neck2.mirror = true;
      setRotation(Neck2, -0.1745329F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 42, 37);
      Neck1.addBox(0F, 0F, 0F, 4, 6, 10);
      Neck1.setRotationPoint(-2F, 1.5F, -18F);
      Neck1.setTextureSize(128, 128);
      Neck1.mirror = true;
      setRotation(Neck1, -0.1047198F, 0F, 0F);
      Body = new ModelRenderer(this, 70, 11);
      Body.addBox(-3.5F, -2F, -3F, 9, 12, 17);
      Body.setRotationPoint(-1F, 1F, 0F);
      Body.setTextureSize(128, 128);
      Body.mirror = true;
      setRotation(Body, 0.0698132F, 0F, 0F);
      Chest = new ModelRenderer(this, 1, 24);
      Chest.addBox(0F, -1F, 2F, 8, 10, 10);
      Chest.setRotationPoint(-4F, 2F, -12F);
      Chest.setTextureSize(128, 128);
      Chest.mirror = true;
      setRotation(Chest, 0.1047198F, 0F, 0F);
      RightArmUpper = new ModelRenderer(this, 93, 44);
      RightArmUpper.addBox(-1F, 0F, -1F, 2, 5, 3);
      RightArmUpper.setRotationPoint(-4.5F, 8F, -8F);
      RightArmUpper.setTextureSize(128, 128);
      RightArmUpper.mirror = true;
      setRotation(RightArmUpper, 0.5235988F, 0F, 0F);
      RightArmLower = new ModelRenderer(this, 86, 55);
      RightArmLower.addBox(-1F, 5F, -5F, 2, 2, 6);
      RightArmLower.setRotationPoint(-4.5F, 8F, -8F);
      RightArmLower.setTextureSize(128, 128);
      RightArmLower.mirror = true;
      setRotation(RightArmLower, 0.5235988F, 0F, 0F);
      RightHand = new ModelRenderer(this, 93, 65);
      RightHand.addBox(-1F, 5F, -8F, 1, 2, 3);
      RightHand.setRotationPoint(-4.5F, 8F, -8F);
      RightHand.setTextureSize(128, 128);
      RightHand.mirror = true;
      setRotation(RightHand, 0.5235988F, -0.1570796F, 0F);
      RightClaw = new ModelRenderer(this, 93, 71);
      RightClaw.addBox(-1F, 6F, -7F, 2, 1, 3);
      RightClaw.setRotationPoint(-4.5F, 8F, -8F);
      RightClaw.setTextureSize(128, 128);
      RightClaw.mirror = true;
      setRotation(RightClaw, 0.3141593F, -0.1570796F, 0F);
      LeftArmUpper = new ModelRenderer(this, 104, 44);
      LeftArmUpper.addBox(-1F, 0F, -1F, 2, 5, 3);
      LeftArmUpper.setRotationPoint(4.5F, 8F, -8F);
      LeftArmUpper.setTextureSize(128, 128);
      LeftArmUpper.mirror = true;
      setRotation(LeftArmUpper, 0.5410521F, 0F, 0F);
      LeftArmLower = new ModelRenderer(this, 109, 55);
      LeftArmLower.addBox(-1F, 5F, -5F, 2, 2, 6);
      LeftArmLower.setRotationPoint(4.5F, 8F, -8F);
      LeftArmLower.setTextureSize(128, 128);
      LeftArmLower.mirror = true;
      setRotation(LeftArmLower, 0.5235988F, 0F, 0F);
      LeftHand = new ModelRenderer(this, 104, 65);
      LeftHand.addBox(0F, 5F, -8F, 1, 2, 3);
      LeftHand.setRotationPoint(4.5F, 8F, -8F);
      LeftHand.setTextureSize(128, 128);
      LeftHand.mirror = true;
      setRotation(LeftHand, 0.5235988F, 0.1570796F, 0F);
      LeftClaw = new ModelRenderer(this, 104, 71);
      LeftClaw.addBox(-1F, 6F, -7F, 2, 1, 3);
      LeftClaw.setRotationPoint(4.5F, 8F, -8F);
      LeftClaw.setTextureSize(128, 128);
      LeftClaw.mirror = true;
      setRotation(LeftClaw, 0.3141593F, 0.1570796F, 0F);
      Mane = new ModelRenderer(this, 43, 87);
      Mane.addBox(-1F, -4F, 0F, 1, 4, 16);
      Mane.setRotationPoint(0.5F, -0.5F, -34F);
      Mane.setTextureSize(128, 128);
      Mane.mirror = true;
      setRotation(Mane, -0.1745329F, 0F, 0F);
    TailPiece1 = new ModelRenderer(this, "TailPiece1");
    TailPiece1.setRotationPoint(0F, 2F, 13F);
    setRotation(TailPiece1, 0F, 0F, 0F);
    TailPiece1.mirror = true;
     // TailPiece1.addBox("Tail1", -4F, -4F, 0F, 8, 10, 8);
    ModelRenderer Tail1 = new ModelRenderer(this, 3, 109);
    Tail1.addBox(-4F, -4F, 0F, 8, 10, 8);
      
      
      TailPiece2 = new ModelRenderer(this, "TailPiece2");
    TailPiece2.setRotationPoint(0F, 0F, 8F);
    setRotation(TailPiece2, 0F, 0F, 0F);
    TailPiece2.mirror = true;
     // TailPiece2.addBox("Tail2", -3F, -3F, 0F, 6, 8, 14);
    ModelRenderer Tail2 = new ModelRenderer(this, 1, 54);
    Tail2.addBox(-3F, -3F, 0F, 6, 8, 14);
      
      TailPiece3 = new ModelRenderer(this, "TailPiece3");
    TailPiece3.setRotationPoint(0F, 0F, 14F);
    setRotation(TailPiece3, 0F, 0F, 0F);
    TailPiece3.mirror = true;
      //TailPiece3.addBox("Tail3", -2.5F, -2F, 0F, 5, 6, 14);
    ModelRenderer Tail3 = new ModelRenderer(this, 42, 54);
    Tail3.addBox(-2.5F, -2F, 0F, 5, 6, 14);
      
      TailPiece4 = new ModelRenderer(this, "TailPiece4");
    TailPiece4.setRotationPoint(0F, 1F, 14F);
    setRotation(TailPiece4, 0F, 0F, 0F);
    TailPiece4.mirror = true;
    //  TailPiece4.addBox("Tail4", -2F, -2F, 0F, 4, 4, 15);
    ModelRenderer Tail4 = new ModelRenderer(this, 1, 81);
    Tail4.addBox(-2F, -2F, 0F, 4, 4, 15);
      
      
      TailPiece5 = new ModelRenderer(this, "TailPiece5");
    TailPiece5.setRotationPoint(0F, 0F, 15F);
    setRotation(TailPiece5, 0F, 0F, 0F);
    TailPiece5.mirror = true;
   //   TailPiece5.addBox("Tail5", -1.5F, -1.5F, 0F, 3, 3, 12);
    ModelRenderer Tail5 = new ModelRenderer(this, 25, 77);
    Tail5.addBox(-1.5F, -1.5F, 0F, 3, 3, 12);
      
      
      //   TailPiece4.addChildModelRenderer(TailPiece5);
    //  TailPiece3.addChildModelRenderer(TailPiece4);
     // TailPiece2.addChildModelRenderer(TailPiece3);
     // TailPiece1.addChildModelRenderer(TailPiece2);
     // ModelMasso.addChildModelRenderer(TailPiece1);
    HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0F, 1.5F, -34F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
     // HeadPiece.addBox("Snout", -1F, -2F, -7F, 2, 4, 3);
     // HeadPiece.addBox("Head", -1.5F, -2F, -4F, 3, 4, 4);
     // HeadPiece.addBox("SnoutTip", -1F, -1F, -8F, 2, 3, 1);
    ModelRenderer Snout = new ModelRenderer(this, 13, 16);
    Snout.addBox(-1F, -2F, -7F, 2, 4, 3);
    ModelRenderer Head = new ModelRenderer(this, 1, 1);
    Head.addBox(-1.5F, -2F, -4F, 3, 4, 4);
    ModelRenderer SnoutTip = new ModelRenderer(this, 0, 17);
    SnoutTip.addBox(-1F, -1F, -8F, 2, 3, 1);
      // ModelMasso.addChildModelRenderer(HeadPiece);
    
    
    LeftLegPiece = new ModelRenderer(this, "LeftLegPiece");
    LeftLegPiece.setRotationPoint(3F, 4F, 10F);
    setRotation(LeftLegPiece, 0F, 0F, 0F);
    LeftLegPiece.mirror = true;
   //   LeftLegPiece.addBox("LeftThigh", 0F, -2F, -3F, 3, 12, 7);
    //  LeftLegPiece.addBox("LeftLegLower", 1F, 10F, 2F, 2, 8, 3);
    //  LeftLegPiece.addBox("LeftFoot", 0.5F, 18F, -1F, 3, 2, 6);
      //ModelMasso.addChildModelRenderer(LeftLegPiece);
    ModelRenderer LeftThigh = new ModelRenderer(this, 94, 81);
    LeftThigh.addBox(0F, -2F, -3F, 3, 12, 7);
    ModelRenderer LeftLegLower = new ModelRenderer(this, 94, 110);
    LeftLegLower.addBox(1F, 10F, 2F, 2, 8, 3);
    ModelRenderer LeftFoot = new ModelRenderer(this, 47, 115);
    LeftFoot.addBox(0.5F, 18F, -1F, 3, 2, 6);
    
    RightLegPiece = new ModelRenderer(this, "RightLegPiece");
    RightLegPiece.setRotationPoint(-3F, 4F, 10F);
    setRotation(RightLegPiece, 0F, 0F, 0F);
    RightLegPiece.mirror = true;
    //  RightLegPiece.addBox("RightThigh", -3F, -2F, -3F, 3, 12, 7);
    //  RightLegPiece.addBox("RightLegLower", -3F, 10F, 2F, 2, 8, 3);
   //   RightLegPiece.addBox("RightFoot", -3.5F, 18F, -1F, 3, 2, 6);
     // ModelMasso.addChildModelRenderer(RightLegPiece);
    ModelRenderer RightThigh = new ModelRenderer(this, 71, 81);
    RightThigh.addBox(-3F, -2F, -3F, 3, 12, 7);
    ModelRenderer RightLegLower = new ModelRenderer(this, 71, 111);
    RightLegLower.addBox(-3F, 10F, 2F, 2, 8, 3);
    ModelRenderer RightFoot = new ModelRenderer(this, 47, 115);
    RightFoot.addBox(-3.5F, 18F, -1F, 3, 2, 6);
  
    TailPiece4.addChild(TailPiece5);
    TailPiece3.addChild(TailPiece4);
    TailPiece2.addChild(TailPiece3);
    TailPiece1.addChild(TailPiece2);
    
    TailPiece1.addChild(Tail1);
    TailPiece2.addChild(Tail2);
    TailPiece3.addChild(Tail3);
    TailPiece4.addChild(Tail4);
    TailPiece5.addChild(Tail5);
    HeadPiece.addChild(Snout);
    HeadPiece.addChild(Head);
    HeadPiece.addChild(SnoutTip);
    LeftLegPiece.addChild(LeftThigh);
    LeftLegPiece.addChild(LeftLegLower);
    LeftLegPiece.addChild(LeftFoot);
    RightLegPiece.addChild(RightThigh);
    RightLegPiece.addChild(RightLegLower);
    RightLegPiece.addChild(RightFoot);
  
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Neck2.render(f5);
    Neck1.render(f5);
    Body.render(f5);
    Chest.render(f5);
    RightArmUpper.render(f5);
    RightArmLower.render(f5);
    RightHand.render(f5);
    RightClaw.render(f5);
    LeftArmUpper.render(f5);
    LeftArmLower.render(f5);
    LeftHand.render(f5);
    LeftClaw.render(f5);
    Mane.render(f5);
    TailPiece1.render(f5);
    HeadPiece.render(f5);
    LeftLegPiece.render(f5);
    RightLegPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    HeadPiece.rotateAngleY = f3 / 57.29578F;
	  HeadPiece.rotateAngleX = f4 / 57.29578F;
	  this.LeftLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	   this.RightLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
