// Date: 12/28/2014 10:43:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelQuetzalcoatlus extends ModelBase
{
  //fields
    ModelRenderer Tail;
    ModelRenderer LowerBody;
    ModelRenderer UpperBody;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer TailTip;
    ModelRenderer RightLeg1;
    ModelRenderer RightLeg2;
    ModelRenderer RightFoot;
    ModelRenderer LeftLeg2;
    ModelRenderer LeftLeg1;
    ModelRenderer LeftFoot;
    ModelRenderer HeadPiece;
    ModelRenderer RightWingPiece;
    ModelRenderer LeftWingPiece;
  ModelRenderer Head;
  ModelRenderer Crest;
  ModelRenderer Beak1;
  ModelRenderer Beak2;
  ModelRenderer Beak3;
 ModelRenderer RightWing1;
 ModelRenderer RightArm1;
    ModelRenderer RightWingPiece2;
    ModelRenderer RightArm2;
    ModelRenderer RightWing2;
    ModelRenderer RightWingPiece3;
    ModelRenderer RightArm3;
    ModelRenderer RightWing3;
    ModelRenderer RightArm4;
    ModelRenderer RightWing4;
    ModelRenderer RightHand;
    ModelRenderer LeftArm1;
    ModelRenderer LeftWing1;
    ModelRenderer LeftWingPiece2;
    ModelRenderer LeftWing2;
    ModelRenderer LeftArm2;
    ModelRenderer LeftWingPiece3;
    ModelRenderer LeftArm3;
    ModelRenderer LeftWing3;
    ModelRenderer LeftWing4;
    ModelRenderer LeftArm4;
    ModelRenderer LeftHand;
    
    
    
    public ModelQuetzalcoatlus()
  {
    textureWidth = 500;
    textureHeight = 150;
    
      Tail = new ModelRenderer(this, 3, 93);
      Tail.addBox(0F, -2F, 0F, 3, 2, 5);
      Tail.setRotationPoint(-1.5F, 18.5F, 11F);
      Tail.setTextureSize(500, 150);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 108, 104);
      LowerBody.addBox(-4.5F, -2F, 11F, 9, 7, 7);
      LowerBody.setRotationPoint(0F, 18F, -7F);
      LowerBody.setTextureSize(500, 150);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      UpperBody = new ModelRenderer(this, 95, 81);
      UpperBody.addBox(-5F, -2F, 0F, 10, 8, 11);
      UpperBody.setRotationPoint(0F, 18F, -7F);
      UpperBody.setTextureSize(500, 150);
      UpperBody.mirror = true;
      setRotation(UpperBody, 0F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 1, 73);
      Neck1.addBox(-2.5F, -5F, -11F, 5, 7, 10);
      Neck1.setRotationPoint(0F, 21F, -6F);
      Neck1.setTextureSize(500, 150);
      Neck1.mirror = true;
      setRotation(Neck1, 0F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 28, 73);
      Neck2.addBox(-1F, -4F, -33F, 4, 7, 23);
      Neck2.setRotationPoint(-1F, 20F, -7F);
      Neck2.setTextureSize(500, 150);
      Neck2.mirror = true;
      setRotation(Neck2, 0F, 0F, 0F);
      TailTip = new ModelRenderer(this, 3, 104);
      TailTip.addBox(0F, -3F, 4F, 2, 2, 3);
      TailTip.setRotationPoint(-1F, 19.5F, 12F);
      TailTip.setTextureSize(500, 150);
      TailTip.mirror = true;
      setRotation(TailTip, 0F, 0F, 0F);
    //  RightLeg1.mirror = true;
      RightLeg1 = new ModelRenderer(this, 320, 58);
      RightLeg1.addBox(-2.5F, -2F, -2F, 3, 10, 5);
      RightLeg1.setRotationPoint(-3F, 20F, 10F);
      RightLeg1.setTextureSize(500, 150);
      RightLeg1.mirror = true;
      setRotation(RightLeg1, 1.570796F, 0F, 0F);
      RightLeg1.mirror = false;
      RightLeg2 = new ModelRenderer(this, 363, 111);
      RightLeg2.addBox(-2F, 8F, -2F, 2, 14, 3);
      RightLeg2.setRotationPoint(-3F, 19F, 10F);
      RightLeg2.setTextureSize(500, 150);
      RightLeg2.mirror = true;
      setRotation(RightLeg2, 1.570796F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 237, 79);
      RightFoot.addBox(-1F, 0F, -26F, 3, 1, 4);
      RightFoot.setRotationPoint(-3F, 19F, 10F);
      RightFoot.setTextureSize(500, 150);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 3.141593F, 0F);
    //  LeftLeg2.mirror = true;
      LeftLeg2 = new ModelRenderer(this, 363, 111);
      LeftLeg2.addBox(0F, 8F, -2F, 2, 14, 3);
      LeftLeg2.setRotationPoint(3F, 19F, 10F);
      LeftLeg2.setTextureSize(500, 150);
      LeftLeg2.mirror = true;
      setRotation(LeftLeg2, 1.570796F, 0F, 0F);
      LeftLeg2.mirror = false;
      LeftLeg1 = new ModelRenderer(this, 320, 58);
      LeftLeg1.addBox(-0.5333334F, -2F, -2F, 3, 10, 5);
      LeftLeg1.setRotationPoint(3F, 20F, 10F);
      LeftLeg1.setTextureSize(500, 150);
      LeftLeg1.mirror = true;
      setRotation(LeftLeg1, 1.570796F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 237, 79);
      LeftFoot.addBox(-3F, 0F, -26F, 3, 1, 4);
      LeftFoot.setRotationPoint(3F, 19F, 10F);
      LeftFoot.setTextureSize(500, 150);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 3.141593F, 0F);
  
      
      HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0F, 19F, -40F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
  //    HeadPiece.addBox("Head", -2.5F, -3.5F, -11F, 5, 8, 11);
   //   HeadPiece.addBox("Crest", 0F, -9F, -17F, 0, 7, 16);
   //   HeadPiece.addBox("Beak1", -2F, -2.5F, -21F, 4, 7, 10);
  //    HeadPiece.addBox("Beak2", -1.5F, -2F, -30F, 3, 6, 9);
  //    HeadPiece.addBox("Beak3", -1.5F, -1.5F, -39F, 3, 5, 9);
    //  modelQuetz.addChildModelRenderer(HeadPiece);
    ModelRenderer Head = new ModelRenderer(this, 4, 103);
    Head.addBox(-2.5F, -3.5F, -11F, 5, 8, 11);
    ModelRenderer Crest = new ModelRenderer(this, 66, 66);
    Crest.addBox(0F, -9F, -17F, 0, 7, 16);
    ModelRenderer Beak1 = new ModelRenderer(this, 43, 106);
    Beak1.addBox(-2F, -2.5F, -21F, 4, 7, 10);
    ModelRenderer Beak2 = new ModelRenderer(this, 78, 103);
    Beak2.addBox(-1.5F, -2F, -30F, 3, 6, 9);
    ModelRenderer Beak3 = new ModelRenderer(this, 96, 118);
    Beak3.addBox(-1.5F, -1.5F, -39F, 3, 5, 9);
    
    
    RightWingPiece = new ModelRenderer(this, "RightWingPiece");
    RightWingPiece.setRotationPoint(-5F, 19F, -5F);
    setRotation(RightWingPiece, 0F, 0F, 0F);
    RightWingPiece.mirror = true;
     // RightWingPiece.addBox("RightWing1", -8F, 0F, 3F, 9, 1, 27);
     // RightWingPiece.addBox("RightArm1", -8F, -1.5F, -2F, 8, 4, 5);
    ModelRenderer RightWing1 = new ModelRenderer(this, -20, 40);
    RightWing1.addBox(-8F, 0F, 3F, 9, 1, 27);
    ModelRenderer RightArm1 = new ModelRenderer(this, 14, 124);
    RightArm1.addBox(-8F, -1.5F, -2F, 8, 4, 5);
      
      
      RightWingPiece2 = new ModelRenderer(this, "RightWingPiece2");
    RightWingPiece2.setRotationPoint(-8F, 0F, 0F);
    setRotation(RightWingPiece2, 0F, 0F, 0F);
    RightWingPiece2.mirror = true;
    //  RightWingPiece2.addBox("RightArm2", -12F, -1F, -2F, 12, 3, 4);
    //  RightWingPiece2.addBox("RightWing2", -12F, 0F, 2F, 12, 1, 30);
    ModelRenderer RightArm2 = new ModelRenderer(this, 7, 136);
    RightArm2.addBox(-12F, -1F, -2F, 12, 3, 4);
    ModelRenderer RightWing2 = new ModelRenderer(this, 39, 34);
    RightWing2.addBox(-12F, 0F, 2F, 12, 1, 30);
      
      
      
      RightWingPiece3 = new ModelRenderer(this, "RightWingPiece3");
    RightWingPiece3.setRotationPoint(-12F, 0F, -1F);
    setRotation(RightWingPiece3, 0F, 0F, 0F);
    RightWingPiece3.mirror = true;
   //   RightWingPiece3.addBox("RightArm3", -13F, -1F, -1F, 13, 3, 3);
   //   RightWingPiece3.addBox("RightWing3", -13F, 0F, 2F, 13, 1, 31);
    //  RightWingPiece3.addBox("RightArm4", -43F, -0.5F, -1F, 30, 2, 2);
    //  RightWingPiece3.addBox("RightWing4", -43F, 0F, 1F, 30, 1, 21);
   //   RightWingPiece3.addBox("RightHand", -13F, 0F, -4F, 3, 1, 3);
    //  RightWingPiece2.addChildModelRenderer(RightWingPiece3);
    //  RightWingPiece.addChildModelRenderer(RightWingPiece2);
    //  modelQuetz.addChildModelRenderer(RightWingPiece);
    ModelRenderer RightArm3 = new ModelRenderer(this, 52, 123);
    RightArm3.addBox(-13F, -1F, -1F, 13, 3, 3);
    ModelRenderer RightWing3 = new ModelRenderer(this, 103, 32);
    RightWing3.addBox(-13F, 0F, 2F, 13, 1, 31);
    ModelRenderer RightArm4 = new ModelRenderer(this, 52, 134);
    RightArm4.addBox(-43F, -0.5F, -1F, 30, 2, 2);
    ModelRenderer RightWing4 = new ModelRenderer(this, 187, 37);
    RightWing4.addBox(-43F, 0F, 1F, 30, 1, 21);
    ModelRenderer RightHand = new ModelRenderer(this, 18, 145);
    RightHand.addBox(-13F, 0F, -4F, 3, 1, 3);
    
    
    
    LeftWingPiece = new ModelRenderer(this, "LeftWingPiece");
    LeftWingPiece.setRotationPoint(5F, 19F, -5F);
    setRotation(LeftWingPiece, 0F, 0F, 0F);
    LeftWingPiece.mirror = true;
     // LeftWingPiece.addBox("LeftArm1", 0F, -1.5F, -2F, 8, 4, 5);
    //  LeftWingPiece.addBox("LeftWing1", -1F, 0F, 3F, 9, 1, 27);
    ModelRenderer LeftArm1 = new ModelRenderer(this, 14, 124);
    LeftArm1.addBox(0F, -1.5F, -2F, 8, 4, 5);
    ModelRenderer LeftWing1 = new ModelRenderer(this, -23, 2);
    LeftWing1.addBox(-1F, 0F, 3F, 9, 1, 27);
      
      
      
      
      LeftWingPiece2 = new ModelRenderer(this, "LeftWingPiece2");
    LeftWingPiece2.setRotationPoint(8F, 0F, 0F);
    setRotation(LeftWingPiece2, 0F, 0F, 0F);
    LeftWingPiece2.mirror = true;
    //  LeftWingPiece2.addBox("LeftWing2", 0F, 0F, 2F, 12, 1, 30);
     // LeftWingPiece2.addBox("LeftArm2", 0F, -1F, -2F, 12, 3, 4);
    ModelRenderer LeftWing2 = new ModelRenderer(this, 42, 1);
    LeftWing2.addBox(0F, 0F, 2F, 12, 1, 30);
    ModelRenderer LeftArm2 = new ModelRenderer(this, 7, 136);
    LeftArm2.addBox(0F, -1F, -2F, 12, 3, 4);
      
      
      LeftWingPiece3 = new ModelRenderer(this, "LeftWingPiece3");
    LeftWingPiece3.setRotationPoint(12F, 0F, -1F);
    setRotation(LeftWingPiece3, 0F, 0F, 0F);
    LeftWingPiece3.mirror = true;
    //  LeftWingPiece3.addBox("LeftArm3", 0F, -1F, -1F, 13, 3, 3);
   //   LeftWingPiece3.addBox("LeftWing3", 0F, 0F, 2F, 13, 1, 31);
    //  LeftWingPiece3.addBox("LeftWing4", 13F, 0F, 1F, 30, 1, 21);
    //  LeftWingPiece3.addBox("LeftArm4", 13F, -0.5F, -0.5F, 30, 2, 2);
    //  LeftWingPiece3.addBox("LeftHand", 10F, 0F, -4F, 3, 1, 3);
   //   LeftWingPiece2.addChildModelRenderer(LeftWingPiece3);
  //    LeftWingPiece.addChildModelRenderer(LeftWingPiece2);
  //    modelQuetz.addChildModelRenderer(LeftWingPiece);
    ModelRenderer LeftArm3 = new ModelRenderer(this, 52, 123);
    LeftArm3.addBox(0F, -1F, -1F, 13, 3, 3);
    ModelRenderer LeftWing3 = new ModelRenderer(this, 112, 1);
    LeftWing3.addBox(0F, 0F, 2F, 13, 1, 31);
    ModelRenderer LeftWing4 = new ModelRenderer(this, 191, 12);
    LeftWing4.addBox(13F, 0F, 1F, 30, 1, 21);
    ModelRenderer LeftArm4 = new ModelRenderer(this, 52, 134);
    LeftArm4.addBox(13F, -0.5F, -0.5F, 30, 2, 2);
    ModelRenderer LeftHand = new ModelRenderer(this, 18, 145);
    LeftHand.addBox(10F, 0F, -4F, 3, 1, 3);
  
    RightWingPiece2.addChild(RightWingPiece3);
    RightWingPiece.addChild(RightWingPiece2);
    LeftWingPiece2.addChild(LeftWingPiece3);
    LeftWingPiece.addChild(LeftWingPiece2);
 
  
    HeadPiece.addChild(Head);
    HeadPiece.addChild(Crest);
    HeadPiece.addChild(Beak1);
    HeadPiece.addChild(Beak2);
    HeadPiece.addChild(Beak3);
  
    RightWingPiece.addChild(RightWing1);
    RightWingPiece.addChild(RightArm1);
    RightWingPiece2.addChild(RightArm2);
    RightWingPiece2.addChild(RightWing2);
    RightWingPiece3.addChild(RightArm3);
    RightWingPiece3.addChild(RightWing3);
    RightWingPiece3.addChild(RightArm4);
    RightWingPiece3.addChild(RightWing4);
    RightWingPiece3.addChild(RightHand);
  
    LeftWingPiece.addChild(LeftArm1);
    LeftWingPiece.addChild(LeftWing1);
    LeftWingPiece2.addChild(LeftWing2);
    LeftWingPiece2.addChild(LeftArm2);
    LeftWingPiece3.addChild(LeftArm3);
    LeftWingPiece3.addChild(LeftWing3);
    LeftWingPiece3.addChild(LeftWing4);
    LeftWingPiece3.addChild(LeftArm4);
    LeftWingPiece3.addChild(LeftHand);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Tail.render(f5);
    LowerBody.render(f5);
    UpperBody.render(f5);
    Neck1.render(f5);
    Neck2.render(f5);
    TailTip.render(f5);
    RightLeg1.render(f5);
    RightLeg2.render(f5);
    RightFoot.render(f5);
    LeftLeg2.render(f5);
    LeftLeg1.render(f5);
    LeftFoot.render(f5);
    HeadPiece.render(f5);
    RightWingPiece.render(f5);
    LeftWingPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.LeftWingPiece.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
		this.RightWingPiece.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
		 HeadPiece.rotateAngleY = f3 / 57.29578F;
		  HeadPiece.rotateAngleX = f4 / 57.29578F;
  
  }

}
