// Date: 12/13/2014 1:51:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelTroodon extends ModelBase
{
 
	protected double distanceMovedTotal = 50.0D;
	// don't make this too large or animations will be skipped
	protected static final double CYCLES_PER_BLOCK = 1.5D; 
	
	protected int  cycleIndex = 0;
	protected float[][] undulationCycle = new float[][]
	{
			{ 0F, 0F, 0F, 0F , 0F, 0F, 0F, 0F},
			{  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
			{  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
			{  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
			{   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
			{   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
			{   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
			{ -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
			{ -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
			{ -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
			{ -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
			{ -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
			{ -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
			/* {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    {  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
	    {   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
	   { -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
	    { -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	   {   0F, -45F,  45F,  45F,   0F, -45F, -45F,   0F },
	    {  45F, -90F,   0F,  45F,  45F,   0F, -45F, -45F },
	    { 0F, 0F, 0F, 0F , 0F, 0F, 0F, 0F},
		{  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
		{  45F, -45F, -45F,   0F,  45F,  45F,   0F, -45F },
		{   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
		{   0F,  45F, -45F, -45F,   0F,  45F,  45F,   0F },
		{ -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
		{ -45F,  90F,   0F, -45F, -45F,   0F,  45F,  45F },
		{ -45F,  45F,  45F,   0F, -45F, -45F,   0F,  45F },
	    { 0F, 0F, 0F, 0F , 0F, 0F, 0F, 0F},*/
	};
	
	
	
	
	//fields
    ModelRenderer LeftArm1;
    ModelRenderer LeftArm2;
    ModelRenderer RightArm1;
    ModelRenderer RightArm2;
    ModelRenderer Neck1;
    ModelRenderer Neck2;
    ModelRenderer Body;
    ModelRenderer TailPiece1;
    ModelRenderer HeadPiece;
    ModelRenderer LeftLegPiece;
    ModelRenderer RightLegPiece;
  ModelRenderer Tail1;
 ModelRenderer TailPiece2;
 ModelRenderer Tail2;
  ModelRenderer TailPiece3;
  ModelRenderer Tail3;
  ModelRenderer TailPiece4;
  ModelRenderer Tail4;
  ModelRenderer modelTroodon;
  ModelRenderer TailPiece5;
  ModelRenderer Tail5;
  ModelRenderer TailFan;
  ModelRenderer Head;
  ModelRenderer Snout;
  ModelRenderer Crest;
  ModelRenderer SnoutTip;
  ModelRenderer LeftLeg;
  ModelRenderer LeftThigh;
  ModelRenderer LeftClaw;
  ModelRenderer LeftFoot;
  ModelRenderer RightThigh;
  ModelRenderer RightLeg;
  ModelRenderer RightFoot;
  ModelRenderer RightClaw;
  
  public ModelTroodon()
  {
    textureWidth = 139;
    textureHeight = 114;
    
      LeftArm1 = new ModelRenderer(this, 116, 46);
      LeftArm1.addBox(0.5F, 0F, -1F, 1, 3, 3);
      LeftArm1.setRotationPoint(2F, 11F, -4F);
      LeftArm1.setTextureSize(139, 114);
      LeftArm1.mirror = true;
      setRotation(LeftArm1, 0.296706F, 0F, 0F);
      LeftArm2 = new ModelRenderer(this, 103, 53);
      LeftArm2.addBox(0.5F, 3F, -4F, 1, 4, 5);
      LeftArm2.setRotationPoint(2F, 11F, -4F);
      LeftArm2.setTextureSize(139, 114);
      LeftArm2.mirror = true;
      setRotation(LeftArm2, 0.296706F, 0F, 0F);
      RightArm1 = new ModelRenderer(this, 116, 46);
      RightArm1.addBox(-1.5F, 0F, -1F, 1, 3, 3);
      RightArm1.setRotationPoint(-2F, 11F, -4F);
      RightArm1.setTextureSize(139, 114);
      RightArm1.mirror = true;
      setRotation(RightArm1, 0.296706F, 0F, 0F);
      RightArm2 = new ModelRenderer(this, 103, 53);
      RightArm2.addBox(-1.5F, 3F, -4F, 1, 4, 5);
      RightArm2.setRotationPoint(-2F, 11F, -4F);
      RightArm2.setTextureSize(139, 114);
      RightArm2.mirror = true;
      setRotation(RightArm2, 0.296706F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 54, 72);
      Neck1.addBox(-2.5F, -4F, -4F, 3, 5, 4);
      Neck1.setRotationPoint(1F, 13F, -3F);
      Neck1.setTextureSize(139, 114);
      Neck1.mirror = true;
      setRotation(Neck1, -0.3490659F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 3, 62);
      Neck2.addBox(-1F, -2F, -7F, 2, 3, 8);
      Neck2.setRotationPoint(0F, 11F, -6F);
      Neck2.setTextureSize(139, 114);
      Neck2.mirror = true;
      setRotation(Neck2, -0.8203047F, 0F, 0F);
      Body = new ModelRenderer(this, 26, 83);
      Body.addBox(-2.5F, -3F, 0F, 5, 6, 11);
      Body.setRotationPoint(0F, 11F, -5F);
      Body.setTextureSize(139, 114);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
    TailPiece1 = new ModelRenderer(this, "TailPiece1");
    TailPiece1.setRotationPoint(0F, 10F, 6F);
    setRotation(TailPiece1, 0F, 0F, 0F);
    TailPiece1.mirror = true;
     // TailPiece1.addBox("Tail1", -2F, -2F, 0F, 4, 5, 3);
    ModelRenderer Tail1 = new ModelRenderer(this, 39, 59);
    Tail1.addBox(-2F, -2F, 0F, 4, 5, 3);
      
      
      
      
      TailPiece2 = new ModelRenderer(this, "TailPiece2");
    TailPiece2.setRotationPoint(0F, 0F, 3F);
    setRotation(TailPiece2, 0F, 0F, 0F);
    TailPiece2.mirror = true;
    //  TailPiece2.addBox("Tail2", -1.5F, -2F, 0F, 3, 4, 5);
    ModelRenderer Tail2 = new ModelRenderer(this, 62, 58);
    Tail2.addBox(-1.5F, -2F, 0F, 3, 4, 5);
      
      
      
      TailPiece3 = new ModelRenderer(this, "TailPiece3");
    TailPiece3.setRotationPoint(0F, -0.5F, 5F);
    setRotation(TailPiece3, 0F, 0F, 0F);
    TailPiece3.mirror = true;
    //  TailPiece3.addBox("Tail3", -1F, -1F, 0F, 2, 3, 8);
    ModelRenderer Tail3 = new ModelRenderer(this, 11, 43);
    Tail3.addBox(-1F, -1F, 0F, 2, 3, 8);
      
      
      TailPiece4 = new ModelRenderer(this, "TailPiece4");
    TailPiece4.setRotationPoint(0F, 0.5F, 8F);
    setRotation(TailPiece4, 0F, 0F, 0F);
    TailPiece4.mirror = true;
     // TailPiece4.addBox("Tail4", -1F, -1F, 0F, 2, 2, 11);
    ModelRenderer Tail4 = new ModelRenderer(this, 39, 40);
    Tail4.addBox(-1F, -1F, 0F, 2, 2, 11);
      
      
      TailPiece5 = new ModelRenderer(this, "TailPiece5");
    TailPiece5.setRotationPoint(0F, 0F, 11F);
    setRotation(TailPiece5, 0F, 0F, 0F);
    TailPiece5.mirror = true;
      //TailPiece5.addBox("Tail5", -1F, -0.5F, 0F, 2, 1, 9);
    //  TailPiece5.addBox("TailFan", -3F, 0F, 3F, 6, 1, 13);
    ModelRenderer Tail5 = new ModelRenderer(this, 71, 42);
    Tail5.addBox(-1F, -0.5F, 0F, 2, 1, 9);
    ModelRenderer TailFan = new ModelRenderer(this, 69, 16);
    TailFan.addBox(-3F, 0F, 3F, 6, 1, 13);
      // TailPiece4.addChildModelRenderer(TailPiece5);
    //  TailPiece3.addChildModelRenderer(TailPiece4);
     // TailPiece2.addChildModelRenderer(TailPiece3);
     // TailPiece1.addChildModelRenderer(TailPiece2);
     // modelTroodon.addChildModelRenderer(TailPiece1);
    HeadPiece = new ModelRenderer(this, "HeadPiece");
    HeadPiece.setRotationPoint(0F, 6F, -10F);
    setRotation(HeadPiece, 0F, 0F, 0F);
    HeadPiece.mirror = true;
     // HeadPiece.addBox("Head", -1.5F, -2F, -4F, 3, 4, 5);
     // HeadPiece.addBox("Snout", -1F, -1F, -8F, 2, 3, 4);
     // HeadPiece.addBox("Crest", 0F, -6F, -4F, 0, 7, 8);
     // HeadPiece.addBox("SnoutTip", -1F, 0F, -9F, 2, 2, 1);
    //  modelTroodon.addChildModelRenderer(HeadPiece);
    ModelRenderer Head = new ModelRenderer(this, 29, 71);
    Head.addBox(-1.5F, -2F, -4F, 3, 4, 5);
    ModelRenderer Snout = new ModelRenderer(this, 14, 76);
    Snout.addBox(-1F, -1F, -8F, 2, 3, 4);
    ModelRenderer Crest = new ModelRenderer(this, 25, 7);
    Crest.addBox(0F, -6F, -4F, 0, 7, 8);
    ModelRenderer SnoutTip = new ModelRenderer(this, 4, 97);
    SnoutTip.addBox(-1F, 0F, -9F, 2, 2, 1);
      
      LeftLegPiece = new ModelRenderer(this, "LeftLegPiece");
    LeftLegPiece.setRotationPoint(1.5F, 11F, 3F);
    setRotation(LeftLegPiece, 0F, 0F, 0F);
    LeftLegPiece.mirror = true;
    //  LeftLegPiece.addBox("LeftLeg", 0F, 5F, 2F, 2, 7, 2);
    //  LeftLegPiece.addBox("LeftThigh", 0F, -2F, -1F, 2, 8, 4);
      //LeftLegPiece.addBox("LeftClaw", 0F, 10F, 0F, 0, 2, 2);
     // LeftLegPiece.addBox("LeftFoot", 0F, 12F, 0F, 2, 1, 4);
    ModelRenderer LeftLeg = new ModelRenderer(this, 55, 30);
    LeftLeg.addBox(0F, 5F, 2F, 2, 7, 2);
    ModelRenderer LeftThigh = new ModelRenderer(this, 34, 27);
    LeftThigh.addBox(0F, -2F, -1F, 2, 8, 4);
    ModelRenderer LeftClaw = new ModelRenderer(this, 20, 0);
    LeftClaw.addBox(0F, 10F, 0F, 0, 2, 2);
    ModelRenderer LeftFoot = new ModelRenderer(this, 64, 30);
    LeftFoot.addBox(0F, 12F, 0F, 2, 1, 4);
     
    
    
    //modelTroodon.addChildModelRenderer(LeftLegPiece);
    RightLegPiece = new ModelRenderer(this, "RightLegPiece");
    RightLegPiece.setRotationPoint(-1.5F, 11F, 3F);
    setRotation(RightLegPiece, 0F, 0F, 0F);
    RightLegPiece.mirror = true;
     
    ModelRenderer RightThigh = new ModelRenderer(this, 48, 13);
    RightThigh.addBox(-2F, -2F, -1F, 2, 8, 4);
    ModelRenderer RightLeg = new ModelRenderer(this, 55, 30);
    RightLeg.addBox(-2F, 5F, 2F, 2, 7, 2);
    ModelRenderer RightFoot = new ModelRenderer(this, 64, 30);
    RightFoot.addBox(-2F, 12F, 0F, 2, 1, 4);
    ModelRenderer RightClaw = new ModelRenderer(this, 20, 0);
    RightClaw.addBox(0F, 10F, 0F, 0, 2, 2);
    //RightLegPiece.addBox("RightThigh", -2F, -2F, -1F, 2, 8, 4);
      RightLeg.mirror = true;
    //  RightLegPiece.addBox("RightLeg", -2F, 5F, 2F, 2, 7, 2);
     // RightLeg.mirror = false;
      RightFoot.mirror = true;
   //   RightLegPiece.addBox("RightFoot", -2F, 12F, 0F, 2, 1, 4);
     // RightFoot.mirror = false;
     // RightLegPiece.addBox("RightClaw", 0F, 10F, 0F, 0, 2, 2);
     // modelTroodon.addChildModelRenderer(RightLegPiece);
 
  
      TailPiece4.addChild(TailPiece5);
      TailPiece3.addChild(TailPiece4);
      TailPiece2.addChild(TailPiece3);
      TailPiece1.addChild(TailPiece2);
  
 
      TailPiece1.addChild(Tail1);
      TailPiece2.addChild(Tail2);
      TailPiece3.addChild(Tail3);
      TailPiece4.addChild(Tail4);
      TailPiece5.addChild(Tail5);
      TailPiece5.addChild(TailFan);
      HeadPiece.addChild(Head);
      HeadPiece.addChild(Snout);
      HeadPiece.addChild(Crest);
      HeadPiece.addChild(SnoutTip);
      LeftLegPiece.addChild(LeftLeg);
      LeftLegPiece.addChild(LeftThigh);
      LeftLegPiece.addChild(LeftClaw);
      LeftLegPiece.addChild(LeftFoot);
      RightLegPiece.addChild(RightThigh);
      RightLegPiece.addChild(RightLeg);
      RightLegPiece.addChild(RightFoot);
      RightLegPiece.addChild(RightClaw);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LeftArm1.render(f5);
    LeftArm2.render(f5);
    RightArm1.render(f5);
    RightArm2.render(f5);
    Neck1.render(f5);
    Neck2.render(f5);
    Body.render(f5);
    TailPiece1.render(f5);
    HeadPiece.render(f5);
    LeftLegPiece.render(f5);
    RightLegPiece.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity parEntity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    HeadPiece.rotateAngleY = f3 / 57.29578F;
	  HeadPiece.rotateAngleX = f4 / 57.29578F;
	  this.LeftLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	   this.RightLegPiece.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
	   updateDistanceMovedTotal(parEntity);
	   cycleIndex = (int) ((getDistanceMovedTotal(parEntity)*CYCLES_PER_BLOCK)
	         %undulationCycle.length);
	   // DEBUG THIS WILL SPAM THE CONSOLE. STOP THIS CODE ON MOD RELEASE.
	   /*System.out.println("ModelSpino setRotationAngles(), distanceMoved ="
	         +getDistanceMovedTotal(parEntity)+", cycleIndex ="+cycleIndex);*/
	   TailPiece4.rotateAngleY = degToRad(undulationCycle[cycleIndex][0]) ;
	   TailPiece5.rotateAngleY = degToRad(undulationCycle[cycleIndex][1]) ;
	 //  TailPiece6.rotateAngleY = degToRad(undulationCycle[cycleIndex][2]) ;
	   TailPiece4.rotateAngleY = degToRad(undulationCycle[cycleIndex][2]) ;
	   TailPiece5.rotateAngleY = degToRad(undulationCycle[cycleIndex][3]) ;
	  // TailPiece6.rotateAngleY = degToRad(undulationCycle[cycleIndex][5]) ;
	   TailPiece4.rotateAngleY = degToRad(undulationCycle[cycleIndex][0]) ;
	   TailPiece5.rotateAngleY = degToRad(undulationCycle[cycleIndex][1]) ;
	 //  TailPiece6.rotateAngleY = degToRad(undulationCycle[cycleIndex][2]) ;
	   TailPiece4.rotateAngleY = degToRad(undulationCycle[cycleIndex][3]) ;
	   TailPiece5.rotateAngleY = degToRad(undulationCycle[cycleIndex][4]) ;
	//   TailPiece6.rotateAngleY = degToRad(undulationCycle[cycleIndex][5]) ;
  
  }
  protected void updateDistanceMovedTotal(Entity parEntity) 
  {
      distanceMovedTotal += parEntity.getDistance(parEntity.prevPosX, parEntity.prevPosY, 
            parEntity.prevPosZ);
  }
  
  protected double getDistanceMovedTotal(Entity parEntity) 
  {
      return (distanceMovedTotal);
  }

  protected float degToRad(float degrees)
  {
      return degrees * (float)Math.PI / 180 ;
  }
}
