// Date: 1/25/2013 10:50:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelBaryonyx extends ModelBase
{
  //fields
    ModelRenderer Spines;
    ModelRenderer Tail6;
    ModelRenderer Tail5;
    ModelRenderer Mane;
    ModelRenderer Tail4;
    ModelRenderer Tail3;
    ModelRenderer Tail2;
    ModelRenderer Tail1;
    ModelRenderer RightClaw;
    ModelRenderer RightHand;
    ModelRenderer RightArmLower;
    ModelRenderer RightArmUpper;
    ModelRenderer LeftClaw;
    ModelRenderer LeftHand;
    ModelRenderer LeftArmLower;
    ModelRenderer LeftArmUpper;
    ModelRenderer Neck2;
    ModelRenderer Neck1;
    ModelRenderer Body;
    ModelRenderer LeftLeg;
    ModelRenderer LeftThigh;
    ModelRenderer LeftFoot;
    ModelRenderer Head;
    ModelRenderer Snout;
    ModelRenderer Nose;
    ModelRenderer Crest;
    ModelRenderer Bump;
    ModelRenderer RightThigh;
    ModelRenderer RightLeg;
    ModelRenderer RightFoot;
  
  public ModelBaryonyx()
  {
    textureWidth = 100;
    textureHeight = 100;
    
      Spines = new ModelRenderer(this, 24, 41);
      Spines.addBox(0F, 0F, 0F, 0, 7, 28);
      Spines.setRotationPoint(0F, -6F, -8F);
      Spines.setTextureSize(100, 100);
      Spines.mirror = true;
      setRotation(Spines, 0F, 0F, 0F);
      Tail6 = new ModelRenderer(this, 74, 25);
      Tail6.addBox(0F, 0F, 0F, 2, 2, 11);
      Tail6.setRotationPoint(-1F, 4F, 48F);
      Tail6.setTextureSize(100, 100);
      Tail6.mirror = true;
      setRotation(Tail6, 0.0174533F, 0F, 0F);
      Tail5 = new ModelRenderer(this, 33, 21);
      Tail5.addBox(0F, 0F, 0F, 3, 3, 11);
      Tail5.setRotationPoint(-1.5F, 3F, 38F);
      Tail5.setTextureSize(100, 100);
      Tail5.mirror = true;
      setRotation(Tail5, -0.0698132F, 0F, 0F);
      Mane = new ModelRenderer(this, 56, 71);
      Mane.addBox(0F, 0F, 0F, 0, 5, 8);
      Mane.setRotationPoint(0F, -5F, -14F);
      Mane.setTextureSize(100, 100);
      Mane.mirror = true;
      setRotation(Mane, -0.3141593F, 0F, 0F);
      Tail4 = new ModelRenderer(this, 70, 39);
      Tail4.addBox(0F, 0F, 0F, 4, 4, 11);
      Tail4.setRotationPoint(-2F, 2F, 28F);
      Tail4.setTextureSize(100, 100);
      Tail4.mirror = true;
      setRotation(Tail4, -0.0872665F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 0, 26);
      Tail3.addBox(0F, 0F, 0F, 5, 5, 11);
      Tail3.setRotationPoint(-2.5F, 1F, 20F);
      Tail3.setTextureSize(100, 100);
      Tail3.mirror = true;
      setRotation(Tail3, -0.0698132F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 9, 55);
      Tail2.addBox(0F, 0F, 0F, 6, 6, 4);
      Tail2.setRotationPoint(-3F, 1F, 16F);
      Tail2.setTextureSize(100, 100);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 29, 43);
      Tail1.addBox(0F, 0F, 0F, 6, 8, 4);
      Tail1.setRotationPoint(-3F, 1F, 12F);
      Tail1.setTextureSize(100, 100);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      RightClaw = new ModelRenderer(this, 26, 80);
      RightClaw.addBox(-2F, 2F, -5F, 2, 4, 1);
      RightClaw.setRotationPoint(-4F, 19F, -5F);
      RightClaw.setTextureSize(100, 100);
      RightClaw.mirror = true;
      setRotation(RightClaw, -1.117011F, -0.418879F, -0.3490659F);
      //RightHand.mirror = true;
      RightHand = new ModelRenderer(this, 54, 88);
      RightHand.addBox(-1F, 0F, -5F, 1, 2, 3);
      RightHand.setRotationPoint(-5F, 14F, -8F);
      RightHand.setTextureSize(100, 100);
      RightHand.mirror = true;
      setRotation(RightHand, 0.7504916F, -0.3665191F, -0.3490659F);
      //RightHand.mirror = false;
      RightArmLower = new ModelRenderer(this, 1, 47);
      RightArmLower.addBox(-1F, 0F, -5F, 1, 2, 5);
      RightArmLower.setRotationPoint(-4F, 12F, -6F);
      RightArmLower.setTextureSize(100, 100);
      RightArmLower.mirror = true;
      setRotation(RightArmLower, 0.8203047F, -0.0174533F, 0F);
      RightArmUpper = new ModelRenderer(this, 1, 48);
      RightArmUpper.addBox(-1F, 0F, 0F, 2, 5, 2);
      RightArmUpper.setRotationPoint(-4F, 8F, -7F);
      RightArmUpper.setTextureSize(100, 100);
      RightArmUpper.mirror = true;
      setRotation(RightArmUpper, 0F, 0F, 0F);
      LeftClaw = new ModelRenderer(this, 21, 80);
      LeftClaw.addBox(0F, 2F, -5F, 2, 4, 1);
      LeftClaw.setRotationPoint(4F, 19F, -5F);
      LeftClaw.setTextureSize(100, 100);
      LeftClaw.mirror = true;
      setRotation(LeftClaw, -1.117011F, 0.418879F, 0.3490659F);
      LeftHand = new ModelRenderer(this, 54, 88);
      LeftHand.addBox(0F, 0F, -5F, 1, 2, 3);
      LeftHand.setRotationPoint(5F, 14F, -8F);
      LeftHand.setTextureSize(100, 100);
      LeftHand.mirror = true;
      setRotation(LeftHand, 0.7504916F, 0.3839724F, 0.3490659F);
      LeftArmLower = new ModelRenderer(this, 1, 47);
      LeftArmLower.addBox(0F, 0F, -5F, 1, 2, 5);
      LeftArmLower.setRotationPoint(4F, 12F, -6F);
      LeftArmLower.setTextureSize(100, 100);
      LeftArmLower.mirror = true;
      setRotation(LeftArmLower, 0.8203047F, 0F, 0F);
      LeftArmUpper = new ModelRenderer(this, 1, 48);
      LeftArmUpper.addBox(-1F, 0F, 0F, 2, 5, 2);
      LeftArmUpper.setRotationPoint(4F, 8F, -7F);
      LeftArmUpper.setTextureSize(100, 100);
      LeftArmUpper.mirror = true;
      setRotation(LeftArmUpper, 0F, 0F, 0F);
      Neck2 = new ModelRenderer(this, 65, 87);
      Neck2.addBox(-1F, -2F, -7F, 4, 5, 8);
      Neck2.setRotationPoint(-1F, 4F, -10F);
      Neck2.setTextureSize(100, 100);
      Neck2.mirror = true;
      setRotation(Neck2, -0.5410521F, 0F, 0F);
      Neck1 = new ModelRenderer(this, 84, 74);
      Neck1.addBox(-2F, -4F, -4F, 6, 7, 4);
      Neck1.setRotationPoint(-1F, 6F, -7F);
      Neck1.setTextureSize(100, 100);
      Neck1.mirror = true;
      setRotation(Neck1, -0.3141593F, 0F, 0F);
      Body = new ModelRenderer(this, 30, 36);
      Body.addBox(7F, -3F, 0F, 8, 10, 20);
      Body.setRotationPoint(-11F, 4F, -8F);
      Body.setTextureSize(100, 100);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 1, 44);
      LeftLeg.addBox(1F, 8F, 3F, 2, 9, 3);
      LeftLeg.setRotationPoint(2F, 5F, 6F);
      LeftLeg.setTextureSize(100, 100);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0F, 0F, 0F);
      LeftThigh = new ModelRenderer(this, 63, 17);
      LeftThigh.addBox(0F, -2F, -2F, 3, 11, 7);
      LeftThigh.setRotationPoint(2F, 5F, 6F);
      LeftThigh.setTextureSize(100, 100);
      LeftThigh.mirror = true;
      setRotation(LeftThigh, 0F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 4, 66);
      LeftFoot.addBox(0.5F, 17F, 0F, 3, 2, 6);
      LeftFoot.setRotationPoint(2F, 5F, 6F);
      LeftFoot.setTextureSize(100, 100);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 86);
      Head.addBox(-3F, -2F, -6F, 4, 5, 9);
      Head.setRotationPoint(1F, 0.6F, -18F);
      Head.setTextureSize(100, 100);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Snout = new ModelRenderer(this, 35, 87);
      Snout.addBox(-2.5F, -1F, -15F, 3, 4, 9);
      Snout.setRotationPoint(1F, 0.6F, -18F);
      Snout.setTextureSize(100, 100);
      Snout.mirror = true;
      setRotation(Snout, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 30, 85);
      Nose.addBox(-2.5F, -0.5F, -17F, 3, 3, 2);
      Nose.setRotationPoint(1F, 0.6F, -18F);
      Nose.setTextureSize(100, 100);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      Crest = new ModelRenderer(this, 36, 71);
      Crest.addBox(-1F, -6F, -4F, 0, 4, 8);
      Crest.setRotationPoint(1F, 0.6F, -18F);
      Crest.setTextureSize(100, 100);
      Crest.mirror = true;
      setRotation(Crest, 0F, 0F, 0F);
      Bump = new ModelRenderer(this, 7, 72);
      Bump.addBox(-1F, -3F, -9F, 0, 2, 4);
      Bump.setRotationPoint(1F, 0.6F, -18F);
      Bump.setTextureSize(100, 100);
      Bump.mirror = true;
      setRotation(Bump, 0F, 0F, 0F);
      RightThigh = new ModelRenderer(this, 50, 2);
      RightThigh.addBox(-3F, -2F, -2F, 3, 11, 7);
      RightThigh.setRotationPoint(-2F, 5F, 6F);
      RightThigh.setTextureSize(100, 100);
      RightThigh.mirror = true;
      setRotation(RightThigh, 0F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 1, 44);
      RightLeg.addBox(-3F, 8F, 3F, 2, 9, 3);
      RightLeg.setRotationPoint(-2F, 5F, 6F);
      RightLeg.setTextureSize(100, 100);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 4, 66);
      RightFoot.addBox(-3.5F, 17F, 0F, 3, 2, 6);
      RightFoot.setRotationPoint(-2F, 5F, 6F);
      RightFoot.setTextureSize(100, 100);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Spines.render(f5);
    Tail6.render(f5);
    Tail5.render(f5);
    Mane.render(f5);
    Tail4.render(f5);
    Tail3.render(f5);
    Tail2.render(f5);
    Tail1.render(f5);
    RightClaw.render(f5);
    RightHand.render(f5);
    RightArmLower.render(f5);
    RightArmUpper.render(f5);
    LeftClaw.render(f5);
    LeftHand.render(f5);
    LeftArmLower.render(f5);
    LeftArmUpper.render(f5);
    Neck2.render(f5);
    Neck1.render(f5);
    Body.render(f5);
    LeftLeg.render(f5);
    LeftThigh.render(f5);
    LeftFoot.render(f5);
    Head.render(f5);
    Snout.render(f5);
    Nose.render(f5);
    Crest.render(f5);
    Bump.render(f5);
    RightThigh.render(f5);
    RightLeg.render(f5);
    RightFoot.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
	  this.LeftLeg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	  this.RightLeg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }
}