// Date: 1/14/2013 3:09:31 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fisherman77.paleocraft.common.mobs;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDimorphodon extends ModelBase
{
  //fields
    ModelRenderer LeftWing;
    ModelRenderer Tail;
    ModelRenderer RightLeg;
    ModelRenderer RightWing;
    ModelRenderer LeftLeg;
    ModelRenderer Neck;
    ModelRenderer Body;
    ModelRenderer Head;
    ModelRenderer SnoutTip;
    ModelRenderer Snout;
  
  public ModelDimorphodon()
  {
    textureWidth = 100;
    textureHeight = 100;
    
      LeftWing = new ModelRenderer(this, -17, 0);
      LeftWing.addBox(0F, 0F, -5F, 40, 1, 17);
      LeftWing.setRotationPoint(3F, 7F, 0F);
      LeftWing.setTextureSize(100, 100);
      LeftWing.mirror = true;
      setRotation(LeftWing, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 12, 21);
      Tail.addBox(0F, 0F, 0F, 7, 6, 11);
      Tail.setRotationPoint(-4F, 5F, -1F);
      Tail.setTextureSize(100, 100);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 7, 45);
      RightLeg.addBox(0F, 0F, 0F, 2, 2, 10);
      RightLeg.setRotationPoint(-5F, 7F, 9F);
      RightLeg.setTextureSize(100, 100);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0.0349066F, -0.2268928F, 0F);
      RightWing = new ModelRenderer(this, -17, 83);
      RightWing.addBox(-40F, 0F, -5F, 40, 1, 17);
      RightWing.setRotationPoint(-4F, 7F, 0F);
      RightWing.setTextureSize(100, 100);
      RightWing.mirror = true;
      setRotation(RightWing, 0F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 7, 45);
      LeftLeg.addBox(0F, 0F, 0F, 2, 2, 10);
      LeftLeg.setRotationPoint(2F, 7F, 9F);
      LeftLeg.setTextureSize(100, 100);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0.0349066F, 0.2268928F, 0F);
      Neck = new ModelRenderer(this, 62, 48);
      Neck.addBox(-1F, 0F, 0F, 3, 4, 5);
      Neck.setRotationPoint(-1F, 6F, -6F);
      Neck.setTextureSize(100, 100);
      Neck.mirror = true;
      setRotation(Neck, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 8, 42);
      Body.addBox(0F, 0F, 0F, 9, 1, 35);
      Body.setRotationPoint(-5F, 7F, 9F);
      Body.setTextureSize(100, 100);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 77, 61);
      Head.addBox(-2F, -3F, -8F, 3, 6, 8);
      Head.setRotationPoint(0F, 8F, -6F);
      Head.setTextureSize(100, 100);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      SnoutTip = new ModelRenderer(this, 58, 28);
      SnoutTip.addBox(-2F, -1F, -12F, 3, 4, 2);
      SnoutTip.setRotationPoint(0F, 8F, -6F);
      SnoutTip.setTextureSize(100, 100);
      SnoutTip.mirror = true;
      setRotation(SnoutTip, 0F, 0F, 0F);
      Snout = new ModelRenderer(this, 76, 34);
      Snout.addBox(-2F, -2F, -10F, 3, 5, 2);
      Snout.setRotationPoint(0F, 8F, -6F);
      Snout.setTextureSize(100, 100);
      Snout.mirror = true;
      setRotation(Snout, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    LeftWing.render(f5);
    Tail.render(f5);
    RightLeg.render(f5);
    RightWing.render(f5);
    LeftLeg.render(f5);
    Neck.render(f5);
    Body.render(f5);
    Head.render(f5);
    SnoutTip.render(f5);
    Snout.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
	this.LeftWing.rotateAngleZ = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
	this.RightWing.rotateAngleZ = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
  }

}
